/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export declare namespace DataTypes {
  export type EModeCategoryStruct = {
    ltv: BigNumberish;
    liquidationThreshold: BigNumberish;
    liquidationBonus: BigNumberish;
    priceSource: AddressLike;
    label: string;
  };

  export type EModeCategoryStructOutput = [
    ltv: bigint,
    liquidationThreshold: bigint,
    liquidationBonus: bigint,
    priceSource: string,
    label: string
  ] & {
    ltv: bigint;
    liquidationThreshold: bigint;
    liquidationBonus: bigint;
    priceSource: string;
    label: string;
  };

  export type ReserveConfigurationMapStruct = { data: BigNumberish };

  export type ReserveConfigurationMapStructOutput = [data: bigint] & {
    data: bigint;
  };

  export type ReserveDataStruct = {
    configuration: DataTypes.ReserveConfigurationMapStruct;
    liquidityIndex: BigNumberish;
    currentLiquidityRate: BigNumberish;
    variableBorrowIndex: BigNumberish;
    currentVariableBorrowRate: BigNumberish;
    currentStableBorrowRate: BigNumberish;
    lastUpdateTimestamp: BigNumberish;
    id: BigNumberish;
    aTokenAddress: AddressLike;
    stableDebtTokenAddress: AddressLike;
    variableDebtTokenAddress: AddressLike;
    interestRateStrategyAddress: AddressLike;
    accruedToTreasury: BigNumberish;
    unbacked: BigNumberish;
    isolationModeTotalDebt: BigNumberish;
  };

  export type ReserveDataStructOutput = [
    configuration: DataTypes.ReserveConfigurationMapStructOutput,
    liquidityIndex: bigint,
    currentLiquidityRate: bigint,
    variableBorrowIndex: bigint,
    currentVariableBorrowRate: bigint,
    currentStableBorrowRate: bigint,
    lastUpdateTimestamp: bigint,
    id: bigint,
    aTokenAddress: string,
    stableDebtTokenAddress: string,
    variableDebtTokenAddress: string,
    interestRateStrategyAddress: string,
    accruedToTreasury: bigint,
    unbacked: bigint,
    isolationModeTotalDebt: bigint
  ] & {
    configuration: DataTypes.ReserveConfigurationMapStructOutput;
    liquidityIndex: bigint;
    currentLiquidityRate: bigint;
    variableBorrowIndex: bigint;
    currentVariableBorrowRate: bigint;
    currentStableBorrowRate: bigint;
    lastUpdateTimestamp: bigint;
    id: bigint;
    aTokenAddress: string;
    stableDebtTokenAddress: string;
    variableDebtTokenAddress: string;
    interestRateStrategyAddress: string;
    accruedToTreasury: bigint;
    unbacked: bigint;
    isolationModeTotalDebt: bigint;
  };

  export type UserConfigurationMapStruct = { data: BigNumberish };

  export type UserConfigurationMapStructOutput = [data: bigint] & {
    data: bigint;
  };
}

export interface IPoolInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ADDRESSES_PROVIDER"
      | "ADDRESSES_PROVIDER()"
      | "BRIDGE_PROTOCOL_FEE"
      | "BRIDGE_PROTOCOL_FEE()"
      | "FLASHLOAN_PREMIUM_TOTAL"
      | "FLASHLOAN_PREMIUM_TOTAL()"
      | "FLASHLOAN_PREMIUM_TO_PROTOCOL"
      | "FLASHLOAN_PREMIUM_TO_PROTOCOL()"
      | "MAX_NUMBER_RESERVES"
      | "MAX_NUMBER_RESERVES()"
      | "MAX_STABLE_RATE_BORROW_SIZE_PERCENT"
      | "MAX_STABLE_RATE_BORROW_SIZE_PERCENT()"
      | "backUnbacked"
      | "backUnbacked(address,uint256,uint256)"
      | "borrow"
      | "borrow(address,uint256,uint256,uint16,address)"
      | "configureEModeCategory"
      | "configureEModeCategory(uint8,(uint16,uint16,uint16,address,string))"
      | "deposit"
      | "deposit(address,uint256,address,uint16)"
      | "dropReserve"
      | "dropReserve(address)"
      | "finalizeTransfer"
      | "finalizeTransfer(address,address,address,uint256,uint256,uint256)"
      | "flashLoan"
      | "flashLoan(address,address[],uint256[],uint256[],address,bytes,uint16)"
      | "flashLoanSimple"
      | "flashLoanSimple(address,address,uint256,bytes,uint16)"
      | "getConfiguration"
      | "getConfiguration(address)"
      | "getEModeCategoryData"
      | "getEModeCategoryData(uint8)"
      | "getReserveAddressById"
      | "getReserveAddressById(uint16)"
      | "getReserveData"
      | "getReserveData(address)"
      | "getReserveNormalizedIncome"
      | "getReserveNormalizedIncome(address)"
      | "getReserveNormalizedVariableDebt"
      | "getReserveNormalizedVariableDebt(address)"
      | "getReservesList"
      | "getReservesList()"
      | "getUserAccountData"
      | "getUserAccountData(address)"
      | "getUserConfiguration"
      | "getUserConfiguration(address)"
      | "getUserEMode"
      | "getUserEMode(address)"
      | "initReserve"
      | "initReserve(address,address,address,address,address)"
      | "liquidationCall"
      | "liquidationCall(address,address,address,uint256,bool)"
      | "mintToTreasury"
      | "mintToTreasury(address[])"
      | "mintUnbacked"
      | "mintUnbacked(address,uint256,address,uint16)"
      | "rebalanceStableBorrowRate"
      | "rebalanceStableBorrowRate(address,address)"
      | "repay"
      | "repay(address,uint256,uint256,address)"
      | "repayWithATokens"
      | "repayWithATokens(address,uint256,uint256)"
      | "repayWithPermit"
      | "repayWithPermit(address,uint256,uint256,address,uint256,uint8,bytes32,bytes32)"
      | "rescueTokens"
      | "rescueTokens(address,address,uint256)"
      | "resetIsolationModeTotalDebt"
      | "resetIsolationModeTotalDebt(address)"
      | "setConfiguration"
      | "setConfiguration(address,(uint256))"
      | "setReserveInterestRateStrategyAddress"
      | "setReserveInterestRateStrategyAddress(address,address)"
      | "setUserEMode"
      | "setUserEMode(uint8)"
      | "setUserUseReserveAsCollateral"
      | "setUserUseReserveAsCollateral(address,bool)"
      | "supply"
      | "supply(address,uint256,address,uint16)"
      | "supplyWithPermit"
      | "supplyWithPermit(address,uint256,address,uint16,uint256,uint8,bytes32,bytes32)"
      | "swapBorrowRateMode"
      | "swapBorrowRateMode(address,uint256)"
      | "updateBridgeProtocolFee"
      | "updateBridgeProtocolFee(uint256)"
      | "updateFlashloanPremiums"
      | "updateFlashloanPremiums(uint128,uint128)"
      | "withdraw"
      | "withdraw(address,uint256,address)"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BackUnbacked"
      | "BackUnbacked(address,address,uint256,uint256)"
      | "Borrow"
      | "Borrow(address,address,address,uint256,uint8,uint256,uint16)"
      | "FlashLoan"
      | "FlashLoan(address,address,address,uint256,uint8,uint256,uint16)"
      | "IsolationModeTotalDebtUpdated"
      | "IsolationModeTotalDebtUpdated(address,uint256)"
      | "LiquidationCall"
      | "LiquidationCall(address,address,address,uint256,uint256,address,bool)"
      | "MintUnbacked"
      | "MintUnbacked(address,address,address,uint256,uint16)"
      | "MintedToTreasury"
      | "MintedToTreasury(address,uint256)"
      | "RebalanceStableBorrowRate"
      | "RebalanceStableBorrowRate(address,address)"
      | "Repay"
      | "Repay(address,address,address,uint256,bool)"
      | "ReserveDataUpdated"
      | "ReserveDataUpdated(address,uint256,uint256,uint256,uint256,uint256)"
      | "ReserveUsedAsCollateralDisabled"
      | "ReserveUsedAsCollateralDisabled(address,address)"
      | "ReserveUsedAsCollateralEnabled"
      | "ReserveUsedAsCollateralEnabled(address,address)"
      | "Supply"
      | "Supply(address,address,address,uint256,uint16)"
      | "SwapBorrowRateMode"
      | "SwapBorrowRateMode(address,address,uint8)"
      | "UserEModeSet"
      | "UserEModeSet(address,uint8)"
      | "Withdraw"
      | "Withdraw(address,address,address,uint256)"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ADDRESSES_PROVIDER",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ADDRESSES_PROVIDER()",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "BRIDGE_PROTOCOL_FEE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "BRIDGE_PROTOCOL_FEE()",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "FLASHLOAN_PREMIUM_TOTAL",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "FLASHLOAN_PREMIUM_TOTAL()",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "FLASHLOAN_PREMIUM_TO_PROTOCOL",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "FLASHLOAN_PREMIUM_TO_PROTOCOL()",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_NUMBER_RESERVES",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_NUMBER_RESERVES()",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_STABLE_RATE_BORROW_SIZE_PERCENT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_STABLE_RATE_BORROW_SIZE_PERCENT()",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "backUnbacked",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "backUnbacked(address,uint256,uint256)",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "borrow",
    values: [AddressLike, BigNumberish, BigNumberish, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "borrow(address,uint256,uint256,uint16,address)",
    values: [AddressLike, BigNumberish, BigNumberish, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "configureEModeCategory",
    values: [BigNumberish, DataTypes.EModeCategoryStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "configureEModeCategory(uint8,(uint16,uint16,uint16,address,string))",
    values: [BigNumberish, DataTypes.EModeCategoryStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [AddressLike, BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deposit(address,uint256,address,uint16)",
    values: [AddressLike, BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "dropReserve",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "dropReserve(address)",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeTransfer",
    values: [
      AddressLike,
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeTransfer(address,address,address,uint256,uint256,uint256)",
    values: [
      AddressLike,
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "flashLoan",
    values: [
      AddressLike,
      AddressLike[],
      BigNumberish[],
      BigNumberish[],
      AddressLike,
      BytesLike,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "flashLoan(address,address[],uint256[],uint256[],address,bytes,uint16)",
    values: [
      AddressLike,
      AddressLike[],
      BigNumberish[],
      BigNumberish[],
      AddressLike,
      BytesLike,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "flashLoanSimple",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "flashLoanSimple(address,address,uint256,bytes,uint16)",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getConfiguration",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getConfiguration(address)",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEModeCategoryData",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEModeCategoryData(uint8)",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getReserveAddressById",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getReserveAddressById(uint16)",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getReserveData",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getReserveData(address)",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getReserveNormalizedIncome",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getReserveNormalizedIncome(address)",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getReserveNormalizedVariableDebt",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getReserveNormalizedVariableDebt(address)",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getReservesList",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getReservesList()",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserAccountData",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserAccountData(address)",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserConfiguration",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserConfiguration(address)",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserEMode",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserEMode(address)",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initReserve",
    values: [AddressLike, AddressLike, AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initReserve(address,address,address,address,address)",
    values: [AddressLike, AddressLike, AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "liquidationCall",
    values: [AddressLike, AddressLike, AddressLike, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "liquidationCall(address,address,address,uint256,bool)",
    values: [AddressLike, AddressLike, AddressLike, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "mintToTreasury",
    values: [AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "mintToTreasury(address[])",
    values: [AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "mintUnbacked",
    values: [AddressLike, BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "mintUnbacked(address,uint256,address,uint16)",
    values: [AddressLike, BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "rebalanceStableBorrowRate",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rebalanceStableBorrowRate(address,address)",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "repay",
    values: [AddressLike, BigNumberish, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "repay(address,uint256,uint256,address)",
    values: [AddressLike, BigNumberish, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "repayWithATokens",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "repayWithATokens(address,uint256,uint256)",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "repayWithPermit",
    values: [
      AddressLike,
      BigNumberish,
      BigNumberish,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "repayWithPermit(address,uint256,uint256,address,uint256,uint8,bytes32,bytes32)",
    values: [
      AddressLike,
      BigNumberish,
      BigNumberish,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "rescueTokens",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "rescueTokens(address,address,uint256)",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "resetIsolationModeTotalDebt",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "resetIsolationModeTotalDebt(address)",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setConfiguration",
    values: [AddressLike, DataTypes.ReserveConfigurationMapStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "setConfiguration(address,(uint256))",
    values: [AddressLike, DataTypes.ReserveConfigurationMapStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "setReserveInterestRateStrategyAddress",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setReserveInterestRateStrategyAddress(address,address)",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setUserEMode",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setUserEMode(uint8)",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setUserUseReserveAsCollateral",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setUserUseReserveAsCollateral(address,bool)",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "supply",
    values: [AddressLike, BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "supply(address,uint256,address,uint16)",
    values: [AddressLike, BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "supplyWithPermit",
    values: [
      AddressLike,
      BigNumberish,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "supplyWithPermit(address,uint256,address,uint16,uint256,uint8,bytes32,bytes32)",
    values: [
      AddressLike,
      BigNumberish,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "swapBorrowRateMode",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "swapBorrowRateMode(address,uint256)",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateBridgeProtocolFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateBridgeProtocolFee(uint256)",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateFlashloanPremiums",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateFlashloanPremiums(uint128,uint128)",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [AddressLike, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw(address,uint256,address)",
    values: [AddressLike, BigNumberish, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "ADDRESSES_PROVIDER",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ADDRESSES_PROVIDER()",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "BRIDGE_PROTOCOL_FEE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "BRIDGE_PROTOCOL_FEE()",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "FLASHLOAN_PREMIUM_TOTAL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "FLASHLOAN_PREMIUM_TOTAL()",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "FLASHLOAN_PREMIUM_TO_PROTOCOL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "FLASHLOAN_PREMIUM_TO_PROTOCOL()",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_NUMBER_RESERVES",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_NUMBER_RESERVES()",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_STABLE_RATE_BORROW_SIZE_PERCENT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_STABLE_RATE_BORROW_SIZE_PERCENT()",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "backUnbacked",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "backUnbacked(address,uint256,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "borrow", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "borrow(address,uint256,uint256,uint16,address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "configureEModeCategory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "configureEModeCategory(uint8,(uint16,uint16,uint16,address,string))",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "deposit(address,uint256,address,uint16)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dropReserve",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dropReserve(address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizeTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "finalizeTransfer(address,address,address,uint256,uint256,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "flashLoan", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "flashLoan(address,address[],uint256[],uint256[],address,bytes,uint16)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "flashLoanSimple",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "flashLoanSimple(address,address,uint256,bytes,uint16)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getConfiguration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getConfiguration(address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEModeCategoryData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEModeCategoryData(uint8)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReserveAddressById",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReserveAddressById(uint16)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReserveData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReserveData(address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReserveNormalizedIncome",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReserveNormalizedIncome(address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReserveNormalizedVariableDebt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReserveNormalizedVariableDebt(address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReservesList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReservesList()",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserAccountData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserAccountData(address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserConfiguration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserConfiguration(address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserEMode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserEMode(address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initReserve",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initReserve(address,address,address,address,address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "liquidationCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "liquidationCall(address,address,address,uint256,bool)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintToTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintToTreasury(address[])",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintUnbacked",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintUnbacked(address,uint256,address,uint16)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rebalanceStableBorrowRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rebalanceStableBorrowRate(address,address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "repay", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "repay(address,uint256,uint256,address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "repayWithATokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "repayWithATokens(address,uint256,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "repayWithPermit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "repayWithPermit(address,uint256,uint256,address,uint256,uint8,bytes32,bytes32)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rescueTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rescueTokens(address,address,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resetIsolationModeTotalDebt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resetIsolationModeTotalDebt(address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setConfiguration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setConfiguration(address,(uint256))",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setReserveInterestRateStrategyAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setReserveInterestRateStrategyAddress(address,address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setUserEMode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setUserEMode(uint8)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setUserUseReserveAsCollateral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setUserUseReserveAsCollateral(address,bool)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "supply", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supply(address,uint256,address,uint16)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supplyWithPermit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supplyWithPermit(address,uint256,address,uint16,uint256,uint8,bytes32,bytes32)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapBorrowRateMode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapBorrowRateMode(address,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateBridgeProtocolFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateBridgeProtocolFee(uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateFlashloanPremiums",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateFlashloanPremiums(uint128,uint128)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdraw(address,uint256,address)",
    data: BytesLike
  ): Result;
}

export namespace BackUnbackedEvent {
  export type InputTuple = [
    reserve: AddressLike,
    backer: AddressLike,
    amount: BigNumberish,
    fee: BigNumberish
  ];
  export type OutputTuple = [
    reserve: string,
    backer: string,
    amount: bigint,
    fee: bigint
  ];
  export interface OutputObject {
    reserve: string;
    backer: string;
    amount: bigint;
    fee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BorrowEvent {
  export type InputTuple = [
    reserve: AddressLike,
    user: AddressLike,
    onBehalfOf: AddressLike,
    amount: BigNumberish,
    interestRateMode: BigNumberish,
    borrowRate: BigNumberish,
    referralCode: BigNumberish
  ];
  export type OutputTuple = [
    reserve: string,
    user: string,
    onBehalfOf: string,
    amount: bigint,
    interestRateMode: bigint,
    borrowRate: bigint,
    referralCode: bigint
  ];
  export interface OutputObject {
    reserve: string;
    user: string;
    onBehalfOf: string;
    amount: bigint;
    interestRateMode: bigint;
    borrowRate: bigint;
    referralCode: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FlashLoanEvent {
  export type InputTuple = [
    target: AddressLike,
    initiator: AddressLike,
    asset: AddressLike,
    amount: BigNumberish,
    interestRateMode: BigNumberish,
    premium: BigNumberish,
    referralCode: BigNumberish
  ];
  export type OutputTuple = [
    target: string,
    initiator: string,
    asset: string,
    amount: bigint,
    interestRateMode: bigint,
    premium: bigint,
    referralCode: bigint
  ];
  export interface OutputObject {
    target: string;
    initiator: string;
    asset: string;
    amount: bigint;
    interestRateMode: bigint;
    premium: bigint;
    referralCode: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IsolationModeTotalDebtUpdatedEvent {
  export type InputTuple = [asset: AddressLike, totalDebt: BigNumberish];
  export type OutputTuple = [asset: string, totalDebt: bigint];
  export interface OutputObject {
    asset: string;
    totalDebt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidationCallEvent {
  export type InputTuple = [
    collateralAsset: AddressLike,
    debtAsset: AddressLike,
    user: AddressLike,
    debtToCover: BigNumberish,
    liquidatedCollateralAmount: BigNumberish,
    liquidator: AddressLike,
    receiveAToken: boolean
  ];
  export type OutputTuple = [
    collateralAsset: string,
    debtAsset: string,
    user: string,
    debtToCover: bigint,
    liquidatedCollateralAmount: bigint,
    liquidator: string,
    receiveAToken: boolean
  ];
  export interface OutputObject {
    collateralAsset: string;
    debtAsset: string;
    user: string;
    debtToCover: bigint;
    liquidatedCollateralAmount: bigint;
    liquidator: string;
    receiveAToken: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MintUnbackedEvent {
  export type InputTuple = [
    reserve: AddressLike,
    user: AddressLike,
    onBehalfOf: AddressLike,
    amount: BigNumberish,
    referralCode: BigNumberish
  ];
  export type OutputTuple = [
    reserve: string,
    user: string,
    onBehalfOf: string,
    amount: bigint,
    referralCode: bigint
  ];
  export interface OutputObject {
    reserve: string;
    user: string;
    onBehalfOf: string;
    amount: bigint;
    referralCode: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MintedToTreasuryEvent {
  export type InputTuple = [reserve: AddressLike, amountMinted: BigNumberish];
  export type OutputTuple = [reserve: string, amountMinted: bigint];
  export interface OutputObject {
    reserve: string;
    amountMinted: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RebalanceStableBorrowRateEvent {
  export type InputTuple = [reserve: AddressLike, user: AddressLike];
  export type OutputTuple = [reserve: string, user: string];
  export interface OutputObject {
    reserve: string;
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RepayEvent {
  export type InputTuple = [
    reserve: AddressLike,
    user: AddressLike,
    repayer: AddressLike,
    amount: BigNumberish,
    useATokens: boolean
  ];
  export type OutputTuple = [
    reserve: string,
    user: string,
    repayer: string,
    amount: bigint,
    useATokens: boolean
  ];
  export interface OutputObject {
    reserve: string;
    user: string;
    repayer: string;
    amount: bigint;
    useATokens: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReserveDataUpdatedEvent {
  export type InputTuple = [
    reserve: AddressLike,
    liquidityRate: BigNumberish,
    stableBorrowRate: BigNumberish,
    variableBorrowRate: BigNumberish,
    liquidityIndex: BigNumberish,
    variableBorrowIndex: BigNumberish
  ];
  export type OutputTuple = [
    reserve: string,
    liquidityRate: bigint,
    stableBorrowRate: bigint,
    variableBorrowRate: bigint,
    liquidityIndex: bigint,
    variableBorrowIndex: bigint
  ];
  export interface OutputObject {
    reserve: string;
    liquidityRate: bigint;
    stableBorrowRate: bigint;
    variableBorrowRate: bigint;
    liquidityIndex: bigint;
    variableBorrowIndex: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReserveUsedAsCollateralDisabledEvent {
  export type InputTuple = [reserve: AddressLike, user: AddressLike];
  export type OutputTuple = [reserve: string, user: string];
  export interface OutputObject {
    reserve: string;
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReserveUsedAsCollateralEnabledEvent {
  export type InputTuple = [reserve: AddressLike, user: AddressLike];
  export type OutputTuple = [reserve: string, user: string];
  export interface OutputObject {
    reserve: string;
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SupplyEvent {
  export type InputTuple = [
    reserve: AddressLike,
    user: AddressLike,
    onBehalfOf: AddressLike,
    amount: BigNumberish,
    referralCode: BigNumberish
  ];
  export type OutputTuple = [
    reserve: string,
    user: string,
    onBehalfOf: string,
    amount: bigint,
    referralCode: bigint
  ];
  export interface OutputObject {
    reserve: string;
    user: string;
    onBehalfOf: string;
    amount: bigint;
    referralCode: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SwapBorrowRateModeEvent {
  export type InputTuple = [
    reserve: AddressLike,
    user: AddressLike,
    interestRateMode: BigNumberish
  ];
  export type OutputTuple = [
    reserve: string,
    user: string,
    interestRateMode: bigint
  ];
  export interface OutputObject {
    reserve: string;
    user: string;
    interestRateMode: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserEModeSetEvent {
  export type InputTuple = [user: AddressLike, categoryId: BigNumberish];
  export type OutputTuple = [user: string, categoryId: bigint];
  export interface OutputObject {
    user: string;
    categoryId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawEvent {
  export type InputTuple = [
    reserve: AddressLike,
    user: AddressLike,
    to: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    reserve: string,
    user: string,
    to: string,
    amount: bigint
  ];
  export interface OutputObject {
    reserve: string;
    user: string;
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IPool extends BaseContract {
  connect(runner?: ContractRunner | null): IPool;
  waitForDeployment(): Promise<this>;

  interface: IPoolInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ADDRESSES_PROVIDER: TypedContractMethod<[], [string], "view">;

  "ADDRESSES_PROVIDER()": TypedContractMethod<[], [string], "view">;

  BRIDGE_PROTOCOL_FEE: TypedContractMethod<[], [bigint], "view">;

  "BRIDGE_PROTOCOL_FEE()": TypedContractMethod<[], [bigint], "view">;

  FLASHLOAN_PREMIUM_TOTAL: TypedContractMethod<[], [bigint], "view">;

  "FLASHLOAN_PREMIUM_TOTAL()": TypedContractMethod<[], [bigint], "view">;

  FLASHLOAN_PREMIUM_TO_PROTOCOL: TypedContractMethod<[], [bigint], "view">;

  "FLASHLOAN_PREMIUM_TO_PROTOCOL()": TypedContractMethod<[], [bigint], "view">;

  MAX_NUMBER_RESERVES: TypedContractMethod<[], [bigint], "view">;

  "MAX_NUMBER_RESERVES()": TypedContractMethod<[], [bigint], "view">;

  MAX_STABLE_RATE_BORROW_SIZE_PERCENT: TypedContractMethod<
    [],
    [bigint],
    "view"
  >;

  "MAX_STABLE_RATE_BORROW_SIZE_PERCENT()": TypedContractMethod<
    [],
    [bigint],
    "view"
  >;

  backUnbacked: TypedContractMethod<
    [asset: AddressLike, amount: BigNumberish, fee: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  "backUnbacked(address,uint256,uint256)": TypedContractMethod<
    [asset: AddressLike, amount: BigNumberish, fee: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  borrow: TypedContractMethod<
    [
      asset: AddressLike,
      amount: BigNumberish,
      interestRateMode: BigNumberish,
      referralCode: BigNumberish,
      onBehalfOf: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  "borrow(address,uint256,uint256,uint16,address)": TypedContractMethod<
    [
      asset: AddressLike,
      amount: BigNumberish,
      interestRateMode: BigNumberish,
      referralCode: BigNumberish,
      onBehalfOf: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  configureEModeCategory: TypedContractMethod<
    [id: BigNumberish, config: DataTypes.EModeCategoryStruct],
    [void],
    "nonpayable"
  >;

  "configureEModeCategory(uint8,(uint16,uint16,uint16,address,string))": TypedContractMethod<
    [id: BigNumberish, config: DataTypes.EModeCategoryStruct],
    [void],
    "nonpayable"
  >;

  deposit: TypedContractMethod<
    [
      asset: AddressLike,
      amount: BigNumberish,
      onBehalfOf: AddressLike,
      referralCode: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  "deposit(address,uint256,address,uint16)": TypedContractMethod<
    [
      asset: AddressLike,
      amount: BigNumberish,
      onBehalfOf: AddressLike,
      referralCode: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  dropReserve: TypedContractMethod<[asset: AddressLike], [void], "nonpayable">;

  "dropReserve(address)": TypedContractMethod<
    [asset: AddressLike],
    [void],
    "nonpayable"
  >;

  finalizeTransfer: TypedContractMethod<
    [
      asset: AddressLike,
      from: AddressLike,
      to: AddressLike,
      amount: BigNumberish,
      balanceFromBefore: BigNumberish,
      balanceToBefore: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  "finalizeTransfer(address,address,address,uint256,uint256,uint256)": TypedContractMethod<
    [
      asset: AddressLike,
      from: AddressLike,
      to: AddressLike,
      amount: BigNumberish,
      balanceFromBefore: BigNumberish,
      balanceToBefore: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  flashLoan: TypedContractMethod<
    [
      receiverAddress: AddressLike,
      assets: AddressLike[],
      amounts: BigNumberish[],
      interestRateModes: BigNumberish[],
      onBehalfOf: AddressLike,
      params: BytesLike,
      referralCode: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  "flashLoan(address,address[],uint256[],uint256[],address,bytes,uint16)": TypedContractMethod<
    [
      receiverAddress: AddressLike,
      assets: AddressLike[],
      amounts: BigNumberish[],
      interestRateModes: BigNumberish[],
      onBehalfOf: AddressLike,
      params: BytesLike,
      referralCode: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  flashLoanSimple: TypedContractMethod<
    [
      receiverAddress: AddressLike,
      asset: AddressLike,
      amount: BigNumberish,
      params: BytesLike,
      referralCode: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  "flashLoanSimple(address,address,uint256,bytes,uint16)": TypedContractMethod<
    [
      receiverAddress: AddressLike,
      asset: AddressLike,
      amount: BigNumberish,
      params: BytesLike,
      referralCode: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getConfiguration: TypedContractMethod<
    [asset: AddressLike],
    [DataTypes.ReserveConfigurationMapStructOutput],
    "view"
  >;

  "getConfiguration(address)": TypedContractMethod<
    [asset: AddressLike],
    [DataTypes.ReserveConfigurationMapStructOutput],
    "view"
  >;

  getEModeCategoryData: TypedContractMethod<
    [id: BigNumberish],
    [DataTypes.EModeCategoryStructOutput],
    "view"
  >;

  "getEModeCategoryData(uint8)": TypedContractMethod<
    [id: BigNumberish],
    [DataTypes.EModeCategoryStructOutput],
    "view"
  >;

  getReserveAddressById: TypedContractMethod<
    [id: BigNumberish],
    [string],
    "view"
  >;

  "getReserveAddressById(uint16)": TypedContractMethod<
    [id: BigNumberish],
    [string],
    "view"
  >;

  getReserveData: TypedContractMethod<
    [asset: AddressLike],
    [DataTypes.ReserveDataStructOutput],
    "view"
  >;

  "getReserveData(address)": TypedContractMethod<
    [asset: AddressLike],
    [DataTypes.ReserveDataStructOutput],
    "view"
  >;

  getReserveNormalizedIncome: TypedContractMethod<
    [asset: AddressLike],
    [bigint],
    "view"
  >;

  "getReserveNormalizedIncome(address)": TypedContractMethod<
    [asset: AddressLike],
    [bigint],
    "view"
  >;

  getReserveNormalizedVariableDebt: TypedContractMethod<
    [asset: AddressLike],
    [bigint],
    "view"
  >;

  "getReserveNormalizedVariableDebt(address)": TypedContractMethod<
    [asset: AddressLike],
    [bigint],
    "view"
  >;

  getReservesList: TypedContractMethod<[], [string[]], "view">;

  "getReservesList()": TypedContractMethod<[], [string[]], "view">;

  getUserAccountData: TypedContractMethod<
    [user: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint] & {
        totalCollateralBase: bigint;
        totalDebtBase: bigint;
        availableBorrowsBase: bigint;
        currentLiquidationThreshold: bigint;
        ltv: bigint;
        healthFactor: bigint;
      }
    ],
    "view"
  >;

  "getUserAccountData(address)": TypedContractMethod<
    [user: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint] & {
        totalCollateralBase: bigint;
        totalDebtBase: bigint;
        availableBorrowsBase: bigint;
        currentLiquidationThreshold: bigint;
        ltv: bigint;
        healthFactor: bigint;
      }
    ],
    "view"
  >;

  getUserConfiguration: TypedContractMethod<
    [user: AddressLike],
    [DataTypes.UserConfigurationMapStructOutput],
    "view"
  >;

  "getUserConfiguration(address)": TypedContractMethod<
    [user: AddressLike],
    [DataTypes.UserConfigurationMapStructOutput],
    "view"
  >;

  getUserEMode: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  "getUserEMode(address)": TypedContractMethod<
    [user: AddressLike],
    [bigint],
    "view"
  >;

  initReserve: TypedContractMethod<
    [
      asset: AddressLike,
      aTokenAddress: AddressLike,
      stableDebtAddress: AddressLike,
      variableDebtAddress: AddressLike,
      interestRateStrategyAddress: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  "initReserve(address,address,address,address,address)": TypedContractMethod<
    [
      asset: AddressLike,
      aTokenAddress: AddressLike,
      stableDebtAddress: AddressLike,
      variableDebtAddress: AddressLike,
      interestRateStrategyAddress: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  liquidationCall: TypedContractMethod<
    [
      collateralAsset: AddressLike,
      debtAsset: AddressLike,
      user: AddressLike,
      debtToCover: BigNumberish,
      receiveAToken: boolean
    ],
    [void],
    "nonpayable"
  >;

  "liquidationCall(address,address,address,uint256,bool)": TypedContractMethod<
    [
      collateralAsset: AddressLike,
      debtAsset: AddressLike,
      user: AddressLike,
      debtToCover: BigNumberish,
      receiveAToken: boolean
    ],
    [void],
    "nonpayable"
  >;

  mintToTreasury: TypedContractMethod<
    [assets: AddressLike[]],
    [void],
    "nonpayable"
  >;

  "mintToTreasury(address[])": TypedContractMethod<
    [assets: AddressLike[]],
    [void],
    "nonpayable"
  >;

  mintUnbacked: TypedContractMethod<
    [
      asset: AddressLike,
      amount: BigNumberish,
      onBehalfOf: AddressLike,
      referralCode: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  "mintUnbacked(address,uint256,address,uint16)": TypedContractMethod<
    [
      asset: AddressLike,
      amount: BigNumberish,
      onBehalfOf: AddressLike,
      referralCode: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  rebalanceStableBorrowRate: TypedContractMethod<
    [asset: AddressLike, user: AddressLike],
    [void],
    "nonpayable"
  >;

  "rebalanceStableBorrowRate(address,address)": TypedContractMethod<
    [asset: AddressLike, user: AddressLike],
    [void],
    "nonpayable"
  >;

  repay: TypedContractMethod<
    [
      asset: AddressLike,
      amount: BigNumberish,
      interestRateMode: BigNumberish,
      onBehalfOf: AddressLike
    ],
    [bigint],
    "nonpayable"
  >;

  "repay(address,uint256,uint256,address)": TypedContractMethod<
    [
      asset: AddressLike,
      amount: BigNumberish,
      interestRateMode: BigNumberish,
      onBehalfOf: AddressLike
    ],
    [bigint],
    "nonpayable"
  >;

  repayWithATokens: TypedContractMethod<
    [asset: AddressLike, amount: BigNumberish, interestRateMode: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  "repayWithATokens(address,uint256,uint256)": TypedContractMethod<
    [asset: AddressLike, amount: BigNumberish, interestRateMode: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  repayWithPermit: TypedContractMethod<
    [
      asset: AddressLike,
      amount: BigNumberish,
      interestRateMode: BigNumberish,
      onBehalfOf: AddressLike,
      deadline: BigNumberish,
      permitV: BigNumberish,
      permitR: BytesLike,
      permitS: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  "repayWithPermit(address,uint256,uint256,address,uint256,uint8,bytes32,bytes32)": TypedContractMethod<
    [
      asset: AddressLike,
      amount: BigNumberish,
      interestRateMode: BigNumberish,
      onBehalfOf: AddressLike,
      deadline: BigNumberish,
      permitV: BigNumberish,
      permitR: BytesLike,
      permitS: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  rescueTokens: TypedContractMethod<
    [token: AddressLike, to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  "rescueTokens(address,address,uint256)": TypedContractMethod<
    [token: AddressLike, to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  resetIsolationModeTotalDebt: TypedContractMethod<
    [asset: AddressLike],
    [void],
    "nonpayable"
  >;

  "resetIsolationModeTotalDebt(address)": TypedContractMethod<
    [asset: AddressLike],
    [void],
    "nonpayable"
  >;

  setConfiguration: TypedContractMethod<
    [
      asset: AddressLike,
      configuration: DataTypes.ReserveConfigurationMapStruct
    ],
    [void],
    "nonpayable"
  >;

  "setConfiguration(address,(uint256))": TypedContractMethod<
    [
      asset: AddressLike,
      configuration: DataTypes.ReserveConfigurationMapStruct
    ],
    [void],
    "nonpayable"
  >;

  setReserveInterestRateStrategyAddress: TypedContractMethod<
    [asset: AddressLike, rateStrategyAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  "setReserveInterestRateStrategyAddress(address,address)": TypedContractMethod<
    [asset: AddressLike, rateStrategyAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  setUserEMode: TypedContractMethod<
    [categoryId: BigNumberish],
    [void],
    "nonpayable"
  >;

  "setUserEMode(uint8)": TypedContractMethod<
    [categoryId: BigNumberish],
    [void],
    "nonpayable"
  >;

  setUserUseReserveAsCollateral: TypedContractMethod<
    [asset: AddressLike, useAsCollateral: boolean],
    [void],
    "nonpayable"
  >;

  "setUserUseReserveAsCollateral(address,bool)": TypedContractMethod<
    [asset: AddressLike, useAsCollateral: boolean],
    [void],
    "nonpayable"
  >;

  supply: TypedContractMethod<
    [
      asset: AddressLike,
      amount: BigNumberish,
      onBehalfOf: AddressLike,
      referralCode: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  "supply(address,uint256,address,uint16)": TypedContractMethod<
    [
      asset: AddressLike,
      amount: BigNumberish,
      onBehalfOf: AddressLike,
      referralCode: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  supplyWithPermit: TypedContractMethod<
    [
      asset: AddressLike,
      amount: BigNumberish,
      onBehalfOf: AddressLike,
      referralCode: BigNumberish,
      deadline: BigNumberish,
      permitV: BigNumberish,
      permitR: BytesLike,
      permitS: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  "supplyWithPermit(address,uint256,address,uint16,uint256,uint8,bytes32,bytes32)": TypedContractMethod<
    [
      asset: AddressLike,
      amount: BigNumberish,
      onBehalfOf: AddressLike,
      referralCode: BigNumberish,
      deadline: BigNumberish,
      permitV: BigNumberish,
      permitR: BytesLike,
      permitS: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  swapBorrowRateMode: TypedContractMethod<
    [asset: AddressLike, interestRateMode: BigNumberish],
    [void],
    "nonpayable"
  >;

  "swapBorrowRateMode(address,uint256)": TypedContractMethod<
    [asset: AddressLike, interestRateMode: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateBridgeProtocolFee: TypedContractMethod<
    [bridgeProtocolFee: BigNumberish],
    [void],
    "nonpayable"
  >;

  "updateBridgeProtocolFee(uint256)": TypedContractMethod<
    [bridgeProtocolFee: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateFlashloanPremiums: TypedContractMethod<
    [
      flashLoanPremiumTotal: BigNumberish,
      flashLoanPremiumToProtocol: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  "updateFlashloanPremiums(uint128,uint128)": TypedContractMethod<
    [
      flashLoanPremiumTotal: BigNumberish,
      flashLoanPremiumToProtocol: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  withdraw: TypedContractMethod<
    [asset: AddressLike, amount: BigNumberish, to: AddressLike],
    [bigint],
    "nonpayable"
  >;

  "withdraw(address,uint256,address)": TypedContractMethod<
    [asset: AddressLike, amount: BigNumberish, to: AddressLike],
    [bigint],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ADDRESSES_PROVIDER"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ADDRESSES_PROVIDER()"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "BRIDGE_PROTOCOL_FEE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "BRIDGE_PROTOCOL_FEE()"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "FLASHLOAN_PREMIUM_TOTAL"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "FLASHLOAN_PREMIUM_TOTAL()"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "FLASHLOAN_PREMIUM_TO_PROTOCOL"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "FLASHLOAN_PREMIUM_TO_PROTOCOL()"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_NUMBER_RESERVES"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_NUMBER_RESERVES()"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_STABLE_RATE_BORROW_SIZE_PERCENT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_STABLE_RATE_BORROW_SIZE_PERCENT()"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "backUnbacked"
  ): TypedContractMethod<
    [asset: AddressLike, amount: BigNumberish, fee: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "backUnbacked(address,uint256,uint256)"
  ): TypedContractMethod<
    [asset: AddressLike, amount: BigNumberish, fee: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "borrow"
  ): TypedContractMethod<
    [
      asset: AddressLike,
      amount: BigNumberish,
      interestRateMode: BigNumberish,
      referralCode: BigNumberish,
      onBehalfOf: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "borrow(address,uint256,uint256,uint16,address)"
  ): TypedContractMethod<
    [
      asset: AddressLike,
      amount: BigNumberish,
      interestRateMode: BigNumberish,
      referralCode: BigNumberish,
      onBehalfOf: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "configureEModeCategory"
  ): TypedContractMethod<
    [id: BigNumberish, config: DataTypes.EModeCategoryStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "configureEModeCategory(uint8,(uint16,uint16,uint16,address,string))"
  ): TypedContractMethod<
    [id: BigNumberish, config: DataTypes.EModeCategoryStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<
    [
      asset: AddressLike,
      amount: BigNumberish,
      onBehalfOf: AddressLike,
      referralCode: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deposit(address,uint256,address,uint16)"
  ): TypedContractMethod<
    [
      asset: AddressLike,
      amount: BigNumberish,
      onBehalfOf: AddressLike,
      referralCode: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "dropReserve"
  ): TypedContractMethod<[asset: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "dropReserve(address)"
  ): TypedContractMethod<[asset: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "finalizeTransfer"
  ): TypedContractMethod<
    [
      asset: AddressLike,
      from: AddressLike,
      to: AddressLike,
      amount: BigNumberish,
      balanceFromBefore: BigNumberish,
      balanceToBefore: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "finalizeTransfer(address,address,address,uint256,uint256,uint256)"
  ): TypedContractMethod<
    [
      asset: AddressLike,
      from: AddressLike,
      to: AddressLike,
      amount: BigNumberish,
      balanceFromBefore: BigNumberish,
      balanceToBefore: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "flashLoan"
  ): TypedContractMethod<
    [
      receiverAddress: AddressLike,
      assets: AddressLike[],
      amounts: BigNumberish[],
      interestRateModes: BigNumberish[],
      onBehalfOf: AddressLike,
      params: BytesLike,
      referralCode: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "flashLoan(address,address[],uint256[],uint256[],address,bytes,uint16)"
  ): TypedContractMethod<
    [
      receiverAddress: AddressLike,
      assets: AddressLike[],
      amounts: BigNumberish[],
      interestRateModes: BigNumberish[],
      onBehalfOf: AddressLike,
      params: BytesLike,
      referralCode: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "flashLoanSimple"
  ): TypedContractMethod<
    [
      receiverAddress: AddressLike,
      asset: AddressLike,
      amount: BigNumberish,
      params: BytesLike,
      referralCode: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "flashLoanSimple(address,address,uint256,bytes,uint16)"
  ): TypedContractMethod<
    [
      receiverAddress: AddressLike,
      asset: AddressLike,
      amount: BigNumberish,
      params: BytesLike,
      referralCode: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getConfiguration"
  ): TypedContractMethod<
    [asset: AddressLike],
    [DataTypes.ReserveConfigurationMapStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getConfiguration(address)"
  ): TypedContractMethod<
    [asset: AddressLike],
    [DataTypes.ReserveConfigurationMapStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEModeCategoryData"
  ): TypedContractMethod<
    [id: BigNumberish],
    [DataTypes.EModeCategoryStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEModeCategoryData(uint8)"
  ): TypedContractMethod<
    [id: BigNumberish],
    [DataTypes.EModeCategoryStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getReserveAddressById"
  ): TypedContractMethod<[id: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getReserveAddressById(uint16)"
  ): TypedContractMethod<[id: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getReserveData"
  ): TypedContractMethod<
    [asset: AddressLike],
    [DataTypes.ReserveDataStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getReserveData(address)"
  ): TypedContractMethod<
    [asset: AddressLike],
    [DataTypes.ReserveDataStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getReserveNormalizedIncome"
  ): TypedContractMethod<[asset: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getReserveNormalizedIncome(address)"
  ): TypedContractMethod<[asset: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getReserveNormalizedVariableDebt"
  ): TypedContractMethod<[asset: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getReserveNormalizedVariableDebt(address)"
  ): TypedContractMethod<[asset: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getReservesList"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getReservesList()"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getUserAccountData"
  ): TypedContractMethod<
    [user: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint] & {
        totalCollateralBase: bigint;
        totalDebtBase: bigint;
        availableBorrowsBase: bigint;
        currentLiquidationThreshold: bigint;
        ltv: bigint;
        healthFactor: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserAccountData(address)"
  ): TypedContractMethod<
    [user: AddressLike],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint] & {
        totalCollateralBase: bigint;
        totalDebtBase: bigint;
        availableBorrowsBase: bigint;
        currentLiquidationThreshold: bigint;
        ltv: bigint;
        healthFactor: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserConfiguration"
  ): TypedContractMethod<
    [user: AddressLike],
    [DataTypes.UserConfigurationMapStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserConfiguration(address)"
  ): TypedContractMethod<
    [user: AddressLike],
    [DataTypes.UserConfigurationMapStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserEMode"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserEMode(address)"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "initReserve"
  ): TypedContractMethod<
    [
      asset: AddressLike,
      aTokenAddress: AddressLike,
      stableDebtAddress: AddressLike,
      variableDebtAddress: AddressLike,
      interestRateStrategyAddress: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "initReserve(address,address,address,address,address)"
  ): TypedContractMethod<
    [
      asset: AddressLike,
      aTokenAddress: AddressLike,
      stableDebtAddress: AddressLike,
      variableDebtAddress: AddressLike,
      interestRateStrategyAddress: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "liquidationCall"
  ): TypedContractMethod<
    [
      collateralAsset: AddressLike,
      debtAsset: AddressLike,
      user: AddressLike,
      debtToCover: BigNumberish,
      receiveAToken: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "liquidationCall(address,address,address,uint256,bool)"
  ): TypedContractMethod<
    [
      collateralAsset: AddressLike,
      debtAsset: AddressLike,
      user: AddressLike,
      debtToCover: BigNumberish,
      receiveAToken: boolean
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "mintToTreasury"
  ): TypedContractMethod<[assets: AddressLike[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "mintToTreasury(address[])"
  ): TypedContractMethod<[assets: AddressLike[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "mintUnbacked"
  ): TypedContractMethod<
    [
      asset: AddressLike,
      amount: BigNumberish,
      onBehalfOf: AddressLike,
      referralCode: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "mintUnbacked(address,uint256,address,uint16)"
  ): TypedContractMethod<
    [
      asset: AddressLike,
      amount: BigNumberish,
      onBehalfOf: AddressLike,
      referralCode: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rebalanceStableBorrowRate"
  ): TypedContractMethod<
    [asset: AddressLike, user: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rebalanceStableBorrowRate(address,address)"
  ): TypedContractMethod<
    [asset: AddressLike, user: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "repay"
  ): TypedContractMethod<
    [
      asset: AddressLike,
      amount: BigNumberish,
      interestRateMode: BigNumberish,
      onBehalfOf: AddressLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "repay(address,uint256,uint256,address)"
  ): TypedContractMethod<
    [
      asset: AddressLike,
      amount: BigNumberish,
      interestRateMode: BigNumberish,
      onBehalfOf: AddressLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "repayWithATokens"
  ): TypedContractMethod<
    [asset: AddressLike, amount: BigNumberish, interestRateMode: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "repayWithATokens(address,uint256,uint256)"
  ): TypedContractMethod<
    [asset: AddressLike, amount: BigNumberish, interestRateMode: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "repayWithPermit"
  ): TypedContractMethod<
    [
      asset: AddressLike,
      amount: BigNumberish,
      interestRateMode: BigNumberish,
      onBehalfOf: AddressLike,
      deadline: BigNumberish,
      permitV: BigNumberish,
      permitR: BytesLike,
      permitS: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "repayWithPermit(address,uint256,uint256,address,uint256,uint8,bytes32,bytes32)"
  ): TypedContractMethod<
    [
      asset: AddressLike,
      amount: BigNumberish,
      interestRateMode: BigNumberish,
      onBehalfOf: AddressLike,
      deadline: BigNumberish,
      permitV: BigNumberish,
      permitR: BytesLike,
      permitS: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rescueTokens"
  ): TypedContractMethod<
    [token: AddressLike, to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "rescueTokens(address,address,uint256)"
  ): TypedContractMethod<
    [token: AddressLike, to: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "resetIsolationModeTotalDebt"
  ): TypedContractMethod<[asset: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resetIsolationModeTotalDebt(address)"
  ): TypedContractMethod<[asset: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setConfiguration"
  ): TypedContractMethod<
    [
      asset: AddressLike,
      configuration: DataTypes.ReserveConfigurationMapStruct
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setConfiguration(address,(uint256))"
  ): TypedContractMethod<
    [
      asset: AddressLike,
      configuration: DataTypes.ReserveConfigurationMapStruct
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setReserveInterestRateStrategyAddress"
  ): TypedContractMethod<
    [asset: AddressLike, rateStrategyAddress: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setReserveInterestRateStrategyAddress(address,address)"
  ): TypedContractMethod<
    [asset: AddressLike, rateStrategyAddress: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setUserEMode"
  ): TypedContractMethod<[categoryId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setUserEMode(uint8)"
  ): TypedContractMethod<[categoryId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setUserUseReserveAsCollateral"
  ): TypedContractMethod<
    [asset: AddressLike, useAsCollateral: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setUserUseReserveAsCollateral(address,bool)"
  ): TypedContractMethod<
    [asset: AddressLike, useAsCollateral: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supply"
  ): TypedContractMethod<
    [
      asset: AddressLike,
      amount: BigNumberish,
      onBehalfOf: AddressLike,
      referralCode: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supply(address,uint256,address,uint16)"
  ): TypedContractMethod<
    [
      asset: AddressLike,
      amount: BigNumberish,
      onBehalfOf: AddressLike,
      referralCode: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supplyWithPermit"
  ): TypedContractMethod<
    [
      asset: AddressLike,
      amount: BigNumberish,
      onBehalfOf: AddressLike,
      referralCode: BigNumberish,
      deadline: BigNumberish,
      permitV: BigNumberish,
      permitR: BytesLike,
      permitS: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supplyWithPermit(address,uint256,address,uint16,uint256,uint8,bytes32,bytes32)"
  ): TypedContractMethod<
    [
      asset: AddressLike,
      amount: BigNumberish,
      onBehalfOf: AddressLike,
      referralCode: BigNumberish,
      deadline: BigNumberish,
      permitV: BigNumberish,
      permitR: BytesLike,
      permitS: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "swapBorrowRateMode"
  ): TypedContractMethod<
    [asset: AddressLike, interestRateMode: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "swapBorrowRateMode(address,uint256)"
  ): TypedContractMethod<
    [asset: AddressLike, interestRateMode: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateBridgeProtocolFee"
  ): TypedContractMethod<
    [bridgeProtocolFee: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateBridgeProtocolFee(uint256)"
  ): TypedContractMethod<
    [bridgeProtocolFee: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateFlashloanPremiums"
  ): TypedContractMethod<
    [
      flashLoanPremiumTotal: BigNumberish,
      flashLoanPremiumToProtocol: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateFlashloanPremiums(uint128,uint128)"
  ): TypedContractMethod<
    [
      flashLoanPremiumTotal: BigNumberish,
      flashLoanPremiumToProtocol: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<
    [asset: AddressLike, amount: BigNumberish, to: AddressLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdraw(address,uint256,address)"
  ): TypedContractMethod<
    [asset: AddressLike, amount: BigNumberish, to: AddressLike],
    [bigint],
    "nonpayable"
  >;

  getEvent(
    key: "BackUnbacked"
  ): TypedContractEvent<
    BackUnbackedEvent.InputTuple,
    BackUnbackedEvent.OutputTuple,
    BackUnbackedEvent.OutputObject
  >;
  getEvent(
    key: "BackUnbacked(address,address,uint256,uint256)"
  ): TypedContractEvent<
    BackUnbacked_address_address_uint256_uint256_Event.InputTuple,
    BackUnbacked_address_address_uint256_uint256_Event.OutputTuple,
    BackUnbacked_address_address_uint256_uint256_Event.OutputObject
  >;
  getEvent(
    key: "Borrow"
  ): TypedContractEvent<
    BorrowEvent.InputTuple,
    BorrowEvent.OutputTuple,
    BorrowEvent.OutputObject
  >;
  getEvent(
    key: "Borrow(address,address,address,uint256,uint8,uint256,uint16)"
  ): TypedContractEvent<
    Borrow_address_address_address_uint256_uint8_uint256_uint16_Event.InputTuple,
    Borrow_address_address_address_uint256_uint8_uint256_uint16_Event.OutputTuple,
    Borrow_address_address_address_uint256_uint8_uint256_uint16_Event.OutputObject
  >;
  getEvent(
    key: "FlashLoan"
  ): TypedContractEvent<
    FlashLoanEvent.InputTuple,
    FlashLoanEvent.OutputTuple,
    FlashLoanEvent.OutputObject
  >;
  getEvent(
    key: "FlashLoan(address,address,address,uint256,uint8,uint256,uint16)"
  ): TypedContractEvent<
    FlashLoan_address_address_address_uint256_uint8_uint256_uint16_Event.InputTuple,
    FlashLoan_address_address_address_uint256_uint8_uint256_uint16_Event.OutputTuple,
    FlashLoan_address_address_address_uint256_uint8_uint256_uint16_Event.OutputObject
  >;
  getEvent(
    key: "IsolationModeTotalDebtUpdated"
  ): TypedContractEvent<
    IsolationModeTotalDebtUpdatedEvent.InputTuple,
    IsolationModeTotalDebtUpdatedEvent.OutputTuple,
    IsolationModeTotalDebtUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "IsolationModeTotalDebtUpdated(address,uint256)"
  ): TypedContractEvent<
    IsolationModeTotalDebtUpdated_address_uint256_Event.InputTuple,
    IsolationModeTotalDebtUpdated_address_uint256_Event.OutputTuple,
    IsolationModeTotalDebtUpdated_address_uint256_Event.OutputObject
  >;
  getEvent(
    key: "LiquidationCall"
  ): TypedContractEvent<
    LiquidationCallEvent.InputTuple,
    LiquidationCallEvent.OutputTuple,
    LiquidationCallEvent.OutputObject
  >;
  getEvent(
    key: "LiquidationCall(address,address,address,uint256,uint256,address,bool)"
  ): TypedContractEvent<
    LiquidationCall_address_address_address_uint256_uint256_address_bool_Event.InputTuple,
    LiquidationCall_address_address_address_uint256_uint256_address_bool_Event.OutputTuple,
    LiquidationCall_address_address_address_uint256_uint256_address_bool_Event.OutputObject
  >;
  getEvent(
    key: "MintUnbacked"
  ): TypedContractEvent<
    MintUnbackedEvent.InputTuple,
    MintUnbackedEvent.OutputTuple,
    MintUnbackedEvent.OutputObject
  >;
  getEvent(
    key: "MintUnbacked(address,address,address,uint256,uint16)"
  ): TypedContractEvent<
    MintUnbacked_address_address_address_uint256_uint16_Event.InputTuple,
    MintUnbacked_address_address_address_uint256_uint16_Event.OutputTuple,
    MintUnbacked_address_address_address_uint256_uint16_Event.OutputObject
  >;
  getEvent(
    key: "MintedToTreasury"
  ): TypedContractEvent<
    MintedToTreasuryEvent.InputTuple,
    MintedToTreasuryEvent.OutputTuple,
    MintedToTreasuryEvent.OutputObject
  >;
  getEvent(
    key: "MintedToTreasury(address,uint256)"
  ): TypedContractEvent<
    MintedToTreasury_address_uint256_Event.InputTuple,
    MintedToTreasury_address_uint256_Event.OutputTuple,
    MintedToTreasury_address_uint256_Event.OutputObject
  >;
  getEvent(
    key: "RebalanceStableBorrowRate"
  ): TypedContractEvent<
    RebalanceStableBorrowRateEvent.InputTuple,
    RebalanceStableBorrowRateEvent.OutputTuple,
    RebalanceStableBorrowRateEvent.OutputObject
  >;
  getEvent(
    key: "RebalanceStableBorrowRate(address,address)"
  ): TypedContractEvent<
    RebalanceStableBorrowRate_address_address_Event.InputTuple,
    RebalanceStableBorrowRate_address_address_Event.OutputTuple,
    RebalanceStableBorrowRate_address_address_Event.OutputObject
  >;
  getEvent(
    key: "Repay"
  ): TypedContractEvent<
    RepayEvent.InputTuple,
    RepayEvent.OutputTuple,
    RepayEvent.OutputObject
  >;
  getEvent(
    key: "Repay(address,address,address,uint256,bool)"
  ): TypedContractEvent<
    Repay_address_address_address_uint256_bool_Event.InputTuple,
    Repay_address_address_address_uint256_bool_Event.OutputTuple,
    Repay_address_address_address_uint256_bool_Event.OutputObject
  >;
  getEvent(
    key: "ReserveDataUpdated"
  ): TypedContractEvent<
    ReserveDataUpdatedEvent.InputTuple,
    ReserveDataUpdatedEvent.OutputTuple,
    ReserveDataUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ReserveDataUpdated(address,uint256,uint256,uint256,uint256,uint256)"
  ): TypedContractEvent<
    ReserveDataUpdated_address_uint256_uint256_uint256_uint256_uint256_Event.InputTuple,
    ReserveDataUpdated_address_uint256_uint256_uint256_uint256_uint256_Event.OutputTuple,
    ReserveDataUpdated_address_uint256_uint256_uint256_uint256_uint256_Event.OutputObject
  >;
  getEvent(
    key: "ReserveUsedAsCollateralDisabled"
  ): TypedContractEvent<
    ReserveUsedAsCollateralDisabledEvent.InputTuple,
    ReserveUsedAsCollateralDisabledEvent.OutputTuple,
    ReserveUsedAsCollateralDisabledEvent.OutputObject
  >;
  getEvent(
    key: "ReserveUsedAsCollateralDisabled(address,address)"
  ): TypedContractEvent<
    ReserveUsedAsCollateralDisabled_address_address_Event.InputTuple,
    ReserveUsedAsCollateralDisabled_address_address_Event.OutputTuple,
    ReserveUsedAsCollateralDisabled_address_address_Event.OutputObject
  >;
  getEvent(
    key: "ReserveUsedAsCollateralEnabled"
  ): TypedContractEvent<
    ReserveUsedAsCollateralEnabledEvent.InputTuple,
    ReserveUsedAsCollateralEnabledEvent.OutputTuple,
    ReserveUsedAsCollateralEnabledEvent.OutputObject
  >;
  getEvent(
    key: "ReserveUsedAsCollateralEnabled(address,address)"
  ): TypedContractEvent<
    ReserveUsedAsCollateralEnabled_address_address_Event.InputTuple,
    ReserveUsedAsCollateralEnabled_address_address_Event.OutputTuple,
    ReserveUsedAsCollateralEnabled_address_address_Event.OutputObject
  >;
  getEvent(
    key: "Supply"
  ): TypedContractEvent<
    SupplyEvent.InputTuple,
    SupplyEvent.OutputTuple,
    SupplyEvent.OutputObject
  >;
  getEvent(
    key: "Supply(address,address,address,uint256,uint16)"
  ): TypedContractEvent<
    Supply_address_address_address_uint256_uint16_Event.InputTuple,
    Supply_address_address_address_uint256_uint16_Event.OutputTuple,
    Supply_address_address_address_uint256_uint16_Event.OutputObject
  >;
  getEvent(
    key: "SwapBorrowRateMode"
  ): TypedContractEvent<
    SwapBorrowRateModeEvent.InputTuple,
    SwapBorrowRateModeEvent.OutputTuple,
    SwapBorrowRateModeEvent.OutputObject
  >;
  getEvent(
    key: "SwapBorrowRateMode(address,address,uint8)"
  ): TypedContractEvent<
    SwapBorrowRateMode_address_address_uint8_Event.InputTuple,
    SwapBorrowRateMode_address_address_uint8_Event.OutputTuple,
    SwapBorrowRateMode_address_address_uint8_Event.OutputObject
  >;
  getEvent(
    key: "UserEModeSet"
  ): TypedContractEvent<
    UserEModeSetEvent.InputTuple,
    UserEModeSetEvent.OutputTuple,
    UserEModeSetEvent.OutputObject
  >;
  getEvent(
    key: "UserEModeSet(address,uint8)"
  ): TypedContractEvent<
    UserEModeSet_address_uint8_Event.InputTuple,
    UserEModeSet_address_uint8_Event.OutputTuple,
    UserEModeSet_address_uint8_Event.OutputObject
  >;
  getEvent(
    key: "Withdraw"
  ): TypedContractEvent<
    WithdrawEvent.InputTuple,
    WithdrawEvent.OutputTuple,
    WithdrawEvent.OutputObject
  >;
  getEvent(
    key: "Withdraw(address,address,address,uint256)"
  ): TypedContractEvent<
    Withdraw_address_address_address_uint256_Event.InputTuple,
    Withdraw_address_address_address_uint256_Event.OutputTuple,
    Withdraw_address_address_address_uint256_Event.OutputObject
  >;

  filters: {
    "BackUnbacked(address,address,uint256,uint256)": TypedContractEvent<
      BackUnbackedEvent.InputTuple,
      BackUnbackedEvent.OutputTuple,
      BackUnbackedEvent.OutputObject
    >;
    BackUnbacked: TypedContractEvent<
      BackUnbackedEvent.InputTuple,
      BackUnbackedEvent.OutputTuple,
      BackUnbackedEvent.OutputObject
    >;

    "Borrow(address,address,address,uint256,uint8,uint256,uint16)": TypedContractEvent<
      BorrowEvent.InputTuple,
      BorrowEvent.OutputTuple,
      BorrowEvent.OutputObject
    >;
    Borrow: TypedContractEvent<
      BorrowEvent.InputTuple,
      BorrowEvent.OutputTuple,
      BorrowEvent.OutputObject
    >;

    "FlashLoan(address,address,address,uint256,uint8,uint256,uint16)": TypedContractEvent<
      FlashLoanEvent.InputTuple,
      FlashLoanEvent.OutputTuple,
      FlashLoanEvent.OutputObject
    >;
    FlashLoan: TypedContractEvent<
      FlashLoanEvent.InputTuple,
      FlashLoanEvent.OutputTuple,
      FlashLoanEvent.OutputObject
    >;

    "IsolationModeTotalDebtUpdated(address,uint256)": TypedContractEvent<
      IsolationModeTotalDebtUpdatedEvent.InputTuple,
      IsolationModeTotalDebtUpdatedEvent.OutputTuple,
      IsolationModeTotalDebtUpdatedEvent.OutputObject
    >;
    IsolationModeTotalDebtUpdated: TypedContractEvent<
      IsolationModeTotalDebtUpdatedEvent.InputTuple,
      IsolationModeTotalDebtUpdatedEvent.OutputTuple,
      IsolationModeTotalDebtUpdatedEvent.OutputObject
    >;

    "LiquidationCall(address,address,address,uint256,uint256,address,bool)": TypedContractEvent<
      LiquidationCallEvent.InputTuple,
      LiquidationCallEvent.OutputTuple,
      LiquidationCallEvent.OutputObject
    >;
    LiquidationCall: TypedContractEvent<
      LiquidationCallEvent.InputTuple,
      LiquidationCallEvent.OutputTuple,
      LiquidationCallEvent.OutputObject
    >;

    "MintUnbacked(address,address,address,uint256,uint16)": TypedContractEvent<
      MintUnbackedEvent.InputTuple,
      MintUnbackedEvent.OutputTuple,
      MintUnbackedEvent.OutputObject
    >;
    MintUnbacked: TypedContractEvent<
      MintUnbackedEvent.InputTuple,
      MintUnbackedEvent.OutputTuple,
      MintUnbackedEvent.OutputObject
    >;

    "MintedToTreasury(address,uint256)": TypedContractEvent<
      MintedToTreasuryEvent.InputTuple,
      MintedToTreasuryEvent.OutputTuple,
      MintedToTreasuryEvent.OutputObject
    >;
    MintedToTreasury: TypedContractEvent<
      MintedToTreasuryEvent.InputTuple,
      MintedToTreasuryEvent.OutputTuple,
      MintedToTreasuryEvent.OutputObject
    >;

    "RebalanceStableBorrowRate(address,address)": TypedContractEvent<
      RebalanceStableBorrowRateEvent.InputTuple,
      RebalanceStableBorrowRateEvent.OutputTuple,
      RebalanceStableBorrowRateEvent.OutputObject
    >;
    RebalanceStableBorrowRate: TypedContractEvent<
      RebalanceStableBorrowRateEvent.InputTuple,
      RebalanceStableBorrowRateEvent.OutputTuple,
      RebalanceStableBorrowRateEvent.OutputObject
    >;

    "Repay(address,address,address,uint256,bool)": TypedContractEvent<
      RepayEvent.InputTuple,
      RepayEvent.OutputTuple,
      RepayEvent.OutputObject
    >;
    Repay: TypedContractEvent<
      RepayEvent.InputTuple,
      RepayEvent.OutputTuple,
      RepayEvent.OutputObject
    >;

    "ReserveDataUpdated(address,uint256,uint256,uint256,uint256,uint256)": TypedContractEvent<
      ReserveDataUpdatedEvent.InputTuple,
      ReserveDataUpdatedEvent.OutputTuple,
      ReserveDataUpdatedEvent.OutputObject
    >;
    ReserveDataUpdated: TypedContractEvent<
      ReserveDataUpdatedEvent.InputTuple,
      ReserveDataUpdatedEvent.OutputTuple,
      ReserveDataUpdatedEvent.OutputObject
    >;

    "ReserveUsedAsCollateralDisabled(address,address)": TypedContractEvent<
      ReserveUsedAsCollateralDisabledEvent.InputTuple,
      ReserveUsedAsCollateralDisabledEvent.OutputTuple,
      ReserveUsedAsCollateralDisabledEvent.OutputObject
    >;
    ReserveUsedAsCollateralDisabled: TypedContractEvent<
      ReserveUsedAsCollateralDisabledEvent.InputTuple,
      ReserveUsedAsCollateralDisabledEvent.OutputTuple,
      ReserveUsedAsCollateralDisabledEvent.OutputObject
    >;

    "ReserveUsedAsCollateralEnabled(address,address)": TypedContractEvent<
      ReserveUsedAsCollateralEnabledEvent.InputTuple,
      ReserveUsedAsCollateralEnabledEvent.OutputTuple,
      ReserveUsedAsCollateralEnabledEvent.OutputObject
    >;
    ReserveUsedAsCollateralEnabled: TypedContractEvent<
      ReserveUsedAsCollateralEnabledEvent.InputTuple,
      ReserveUsedAsCollateralEnabledEvent.OutputTuple,
      ReserveUsedAsCollateralEnabledEvent.OutputObject
    >;

    "Supply(address,address,address,uint256,uint16)": TypedContractEvent<
      SupplyEvent.InputTuple,
      SupplyEvent.OutputTuple,
      SupplyEvent.OutputObject
    >;
    Supply: TypedContractEvent<
      SupplyEvent.InputTuple,
      SupplyEvent.OutputTuple,
      SupplyEvent.OutputObject
    >;

    "SwapBorrowRateMode(address,address,uint8)": TypedContractEvent<
      SwapBorrowRateModeEvent.InputTuple,
      SwapBorrowRateModeEvent.OutputTuple,
      SwapBorrowRateModeEvent.OutputObject
    >;
    SwapBorrowRateMode: TypedContractEvent<
      SwapBorrowRateModeEvent.InputTuple,
      SwapBorrowRateModeEvent.OutputTuple,
      SwapBorrowRateModeEvent.OutputObject
    >;

    "UserEModeSet(address,uint8)": TypedContractEvent<
      UserEModeSetEvent.InputTuple,
      UserEModeSetEvent.OutputTuple,
      UserEModeSetEvent.OutputObject
    >;
    UserEModeSet: TypedContractEvent<
      UserEModeSetEvent.InputTuple,
      UserEModeSetEvent.OutputTuple,
      UserEModeSetEvent.OutputObject
    >;

    "Withdraw(address,address,address,uint256)": TypedContractEvent<
      WithdrawEvent.InputTuple,
      WithdrawEvent.OutputTuple,
      WithdrawEvent.OutputObject
    >;
    Withdraw: TypedContractEvent<
      WithdrawEvent.InputTuple,
      WithdrawEvent.OutputTuple,
      WithdrawEvent.OutputObject
    >;
  };
}
