/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../../common";

export interface ILendingPoolAddressesProviderInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getAddress"
      | "getAddress(bytes32)"
      | "getEmergencyAdmin"
      | "getEmergencyAdmin()"
      | "getLendingPool"
      | "getLendingPool()"
      | "getLendingPoolCollateralManager"
      | "getLendingPoolCollateralManager()"
      | "getLendingPoolConfigurator"
      | "getLendingPoolConfigurator()"
      | "getLendingRateOracle"
      | "getLendingRateOracle()"
      | "getMarketId"
      | "getMarketId()"
      | "getPoolAdmin"
      | "getPoolAdmin()"
      | "getPriceOracle"
      | "getPriceOracle()"
      | "setAddress"
      | "setAddress(bytes32,address)"
      | "setAddressAsProxy"
      | "setAddressAsProxy(bytes32,address)"
      | "setEmergencyAdmin"
      | "setEmergencyAdmin(address)"
      | "setLendingPoolCollateralManager"
      | "setLendingPoolCollateralManager(address)"
      | "setLendingPoolConfiguratorImpl"
      | "setLendingPoolConfiguratorImpl(address)"
      | "setLendingPoolImpl"
      | "setLendingPoolImpl(address)"
      | "setLendingRateOracle"
      | "setLendingRateOracle(address)"
      | "setMarketId"
      | "setMarketId(string)"
      | "setPoolAdmin"
      | "setPoolAdmin(address)"
      | "setPriceOracle"
      | "setPriceOracle(address)"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AddressSet"
      | "AddressSet(bytes32,address,bool)"
      | "ConfigurationAdminUpdated"
      | "ConfigurationAdminUpdated(address)"
      | "EmergencyAdminUpdated"
      | "EmergencyAdminUpdated(address)"
      | "LendingPoolCollateralManagerUpdated"
      | "LendingPoolCollateralManagerUpdated(address)"
      | "LendingPoolConfiguratorUpdated"
      | "LendingPoolConfiguratorUpdated(address)"
      | "LendingPoolUpdated"
      | "LendingPoolUpdated(address)"
      | "LendingRateOracleUpdated"
      | "LendingRateOracleUpdated(address)"
      | "MarketIdSet"
      | "MarketIdSet(string)"
      | "PriceOracleUpdated"
      | "PriceOracleUpdated(address)"
      | "ProxyCreated"
      | "ProxyCreated(bytes32,address)"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "getAddress",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAddress(bytes32)",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEmergencyAdmin",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEmergencyAdmin()",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLendingPool",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLendingPool()",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLendingPoolCollateralManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLendingPoolCollateralManager()",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLendingPoolConfigurator",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLendingPoolConfigurator()",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLendingRateOracle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLendingRateOracle()",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMarketId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMarketId()",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPoolAdmin",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPoolAdmin()",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPriceOracle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPriceOracle()",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAddress",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setAddress(bytes32,address)",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setAddressAsProxy",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setAddressAsProxy(bytes32,address)",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setEmergencyAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setEmergencyAdmin(address)",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setLendingPoolCollateralManager",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setLendingPoolCollateralManager(address)",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setLendingPoolConfiguratorImpl",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setLendingPoolConfiguratorImpl(address)",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setLendingPoolImpl",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setLendingPoolImpl(address)",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setLendingRateOracle",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setLendingRateOracle(address)",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "setMarketId", values: [string]): string;
  encodeFunctionData(
    functionFragment: "setMarketId(string)",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setPoolAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setPoolAdmin(address)",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setPriceOracle",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setPriceOracle(address)",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "getAddress", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAddress(bytes32)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEmergencyAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEmergencyAdmin()",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLendingPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLendingPool()",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLendingPoolCollateralManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLendingPoolCollateralManager()",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLendingPoolConfigurator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLendingPoolConfigurator()",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLendingRateOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLendingRateOracle()",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMarketId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMarketId()",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPoolAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPoolAdmin()",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPriceOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPriceOracle()",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setAddress", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAddress(bytes32,address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAddressAsProxy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAddressAsProxy(bytes32,address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setEmergencyAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setEmergencyAdmin(address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setLendingPoolCollateralManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setLendingPoolCollateralManager(address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setLendingPoolConfiguratorImpl",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setLendingPoolConfiguratorImpl(address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setLendingPoolImpl",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setLendingPoolImpl(address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setLendingRateOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setLendingRateOracle(address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMarketId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMarketId(string)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPoolAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPoolAdmin(address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPriceOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPriceOracle(address)",
    data: BytesLike
  ): Result;
}

export namespace AddressSetEvent {
  export type InputTuple = [
    id: BytesLike,
    newAddress: AddressLike,
    hasProxy: boolean
  ];
  export type OutputTuple = [id: string, newAddress: string, hasProxy: boolean];
  export interface OutputObject {
    id: string;
    newAddress: string;
    hasProxy: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ConfigurationAdminUpdatedEvent {
  export type InputTuple = [newAddress: AddressLike];
  export type OutputTuple = [newAddress: string];
  export interface OutputObject {
    newAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmergencyAdminUpdatedEvent {
  export type InputTuple = [newAddress: AddressLike];
  export type OutputTuple = [newAddress: string];
  export interface OutputObject {
    newAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LendingPoolCollateralManagerUpdatedEvent {
  export type InputTuple = [newAddress: AddressLike];
  export type OutputTuple = [newAddress: string];
  export interface OutputObject {
    newAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LendingPoolConfiguratorUpdatedEvent {
  export type InputTuple = [newAddress: AddressLike];
  export type OutputTuple = [newAddress: string];
  export interface OutputObject {
    newAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LendingPoolUpdatedEvent {
  export type InputTuple = [newAddress: AddressLike];
  export type OutputTuple = [newAddress: string];
  export interface OutputObject {
    newAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LendingRateOracleUpdatedEvent {
  export type InputTuple = [newAddress: AddressLike];
  export type OutputTuple = [newAddress: string];
  export interface OutputObject {
    newAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketIdSetEvent {
  export type InputTuple = [newMarketId: string];
  export type OutputTuple = [newMarketId: string];
  export interface OutputObject {
    newMarketId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PriceOracleUpdatedEvent {
  export type InputTuple = [newAddress: AddressLike];
  export type OutputTuple = [newAddress: string];
  export interface OutputObject {
    newAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProxyCreatedEvent {
  export type InputTuple = [id: BytesLike, newAddress: AddressLike];
  export type OutputTuple = [id: string, newAddress: string];
  export interface OutputObject {
    id: string;
    newAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ILendingPoolAddressesProvider extends BaseContract {
  connect(runner?: ContractRunner | null): ILendingPoolAddressesProvider;
  waitForDeployment(): Promise<this>;

  interface: ILendingPoolAddressesProviderInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getAddress: TypedContractMethod<[id: BytesLike], [string], "view">;

  "getAddress(bytes32)": TypedContractMethod<[id: BytesLike], [string], "view">;

  getEmergencyAdmin: TypedContractMethod<[], [string], "view">;

  "getEmergencyAdmin()": TypedContractMethod<[], [string], "view">;

  getLendingPool: TypedContractMethod<[], [string], "view">;

  "getLendingPool()": TypedContractMethod<[], [string], "view">;

  getLendingPoolCollateralManager: TypedContractMethod<[], [string], "view">;

  "getLendingPoolCollateralManager()": TypedContractMethod<
    [],
    [string],
    "view"
  >;

  getLendingPoolConfigurator: TypedContractMethod<[], [string], "view">;

  "getLendingPoolConfigurator()": TypedContractMethod<[], [string], "view">;

  getLendingRateOracle: TypedContractMethod<[], [string], "view">;

  "getLendingRateOracle()": TypedContractMethod<[], [string], "view">;

  getMarketId: TypedContractMethod<[], [string], "view">;

  "getMarketId()": TypedContractMethod<[], [string], "view">;

  getPoolAdmin: TypedContractMethod<[], [string], "view">;

  "getPoolAdmin()": TypedContractMethod<[], [string], "view">;

  getPriceOracle: TypedContractMethod<[], [string], "view">;

  "getPriceOracle()": TypedContractMethod<[], [string], "view">;

  setAddress: TypedContractMethod<
    [id: BytesLike, newAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  "setAddress(bytes32,address)": TypedContractMethod<
    [id: BytesLike, newAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  setAddressAsProxy: TypedContractMethod<
    [id: BytesLike, impl: AddressLike],
    [void],
    "nonpayable"
  >;

  "setAddressAsProxy(bytes32,address)": TypedContractMethod<
    [id: BytesLike, impl: AddressLike],
    [void],
    "nonpayable"
  >;

  setEmergencyAdmin: TypedContractMethod<
    [admin: AddressLike],
    [void],
    "nonpayable"
  >;

  "setEmergencyAdmin(address)": TypedContractMethod<
    [admin: AddressLike],
    [void],
    "nonpayable"
  >;

  setLendingPoolCollateralManager: TypedContractMethod<
    [manager: AddressLike],
    [void],
    "nonpayable"
  >;

  "setLendingPoolCollateralManager(address)": TypedContractMethod<
    [manager: AddressLike],
    [void],
    "nonpayable"
  >;

  setLendingPoolConfiguratorImpl: TypedContractMethod<
    [configurator: AddressLike],
    [void],
    "nonpayable"
  >;

  "setLendingPoolConfiguratorImpl(address)": TypedContractMethod<
    [configurator: AddressLike],
    [void],
    "nonpayable"
  >;

  setLendingPoolImpl: TypedContractMethod<
    [pool: AddressLike],
    [void],
    "nonpayable"
  >;

  "setLendingPoolImpl(address)": TypedContractMethod<
    [pool: AddressLike],
    [void],
    "nonpayable"
  >;

  setLendingRateOracle: TypedContractMethod<
    [lendingRateOracle: AddressLike],
    [void],
    "nonpayable"
  >;

  "setLendingRateOracle(address)": TypedContractMethod<
    [lendingRateOracle: AddressLike],
    [void],
    "nonpayable"
  >;

  setMarketId: TypedContractMethod<[marketId: string], [void], "nonpayable">;

  "setMarketId(string)": TypedContractMethod<
    [marketId: string],
    [void],
    "nonpayable"
  >;

  setPoolAdmin: TypedContractMethod<[admin: AddressLike], [void], "nonpayable">;

  "setPoolAdmin(address)": TypedContractMethod<
    [admin: AddressLike],
    [void],
    "nonpayable"
  >;

  setPriceOracle: TypedContractMethod<
    [priceOracle: AddressLike],
    [void],
    "nonpayable"
  >;

  "setPriceOracle(address)": TypedContractMethod<
    [priceOracle: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getAddress"
  ): TypedContractMethod<[id: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getAddress(bytes32)"
  ): TypedContractMethod<[id: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getEmergencyAdmin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getEmergencyAdmin()"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getLendingPool"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getLendingPool()"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getLendingPoolCollateralManager"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getLendingPoolCollateralManager()"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getLendingPoolConfigurator"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getLendingPoolConfigurator()"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getLendingRateOracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getLendingRateOracle()"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getMarketId"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getMarketId()"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getPoolAdmin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getPoolAdmin()"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getPriceOracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getPriceOracle()"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setAddress"
  ): TypedContractMethod<
    [id: BytesLike, newAddress: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAddress(bytes32,address)"
  ): TypedContractMethod<
    [id: BytesLike, newAddress: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAddressAsProxy"
  ): TypedContractMethod<
    [id: BytesLike, impl: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAddressAsProxy(bytes32,address)"
  ): TypedContractMethod<
    [id: BytesLike, impl: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setEmergencyAdmin"
  ): TypedContractMethod<[admin: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setEmergencyAdmin(address)"
  ): TypedContractMethod<[admin: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setLendingPoolCollateralManager"
  ): TypedContractMethod<[manager: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setLendingPoolCollateralManager(address)"
  ): TypedContractMethod<[manager: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setLendingPoolConfiguratorImpl"
  ): TypedContractMethod<[configurator: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setLendingPoolConfiguratorImpl(address)"
  ): TypedContractMethod<[configurator: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setLendingPoolImpl"
  ): TypedContractMethod<[pool: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setLendingPoolImpl(address)"
  ): TypedContractMethod<[pool: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setLendingRateOracle"
  ): TypedContractMethod<
    [lendingRateOracle: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setLendingRateOracle(address)"
  ): TypedContractMethod<
    [lendingRateOracle: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setMarketId"
  ): TypedContractMethod<[marketId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMarketId(string)"
  ): TypedContractMethod<[marketId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPoolAdmin"
  ): TypedContractMethod<[admin: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPoolAdmin(address)"
  ): TypedContractMethod<[admin: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPriceOracle"
  ): TypedContractMethod<[priceOracle: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPriceOracle(address)"
  ): TypedContractMethod<[priceOracle: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "AddressSet"
  ): TypedContractEvent<
    AddressSetEvent.InputTuple,
    AddressSetEvent.OutputTuple,
    AddressSetEvent.OutputObject
  >;
  getEvent(
    key: "AddressSet(bytes32,address,bool)"
  ): TypedContractEvent<
    AddressSet_bytes32_address_bool_Event.InputTuple,
    AddressSet_bytes32_address_bool_Event.OutputTuple,
    AddressSet_bytes32_address_bool_Event.OutputObject
  >;
  getEvent(
    key: "ConfigurationAdminUpdated"
  ): TypedContractEvent<
    ConfigurationAdminUpdatedEvent.InputTuple,
    ConfigurationAdminUpdatedEvent.OutputTuple,
    ConfigurationAdminUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ConfigurationAdminUpdated(address)"
  ): TypedContractEvent<
    ConfigurationAdminUpdated_address_Event.InputTuple,
    ConfigurationAdminUpdated_address_Event.OutputTuple,
    ConfigurationAdminUpdated_address_Event.OutputObject
  >;
  getEvent(
    key: "EmergencyAdminUpdated"
  ): TypedContractEvent<
    EmergencyAdminUpdatedEvent.InputTuple,
    EmergencyAdminUpdatedEvent.OutputTuple,
    EmergencyAdminUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "EmergencyAdminUpdated(address)"
  ): TypedContractEvent<
    EmergencyAdminUpdated_address_Event.InputTuple,
    EmergencyAdminUpdated_address_Event.OutputTuple,
    EmergencyAdminUpdated_address_Event.OutputObject
  >;
  getEvent(
    key: "LendingPoolCollateralManagerUpdated"
  ): TypedContractEvent<
    LendingPoolCollateralManagerUpdatedEvent.InputTuple,
    LendingPoolCollateralManagerUpdatedEvent.OutputTuple,
    LendingPoolCollateralManagerUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "LendingPoolCollateralManagerUpdated(address)"
  ): TypedContractEvent<
    LendingPoolCollateralManagerUpdated_address_Event.InputTuple,
    LendingPoolCollateralManagerUpdated_address_Event.OutputTuple,
    LendingPoolCollateralManagerUpdated_address_Event.OutputObject
  >;
  getEvent(
    key: "LendingPoolConfiguratorUpdated"
  ): TypedContractEvent<
    LendingPoolConfiguratorUpdatedEvent.InputTuple,
    LendingPoolConfiguratorUpdatedEvent.OutputTuple,
    LendingPoolConfiguratorUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "LendingPoolConfiguratorUpdated(address)"
  ): TypedContractEvent<
    LendingPoolConfiguratorUpdated_address_Event.InputTuple,
    LendingPoolConfiguratorUpdated_address_Event.OutputTuple,
    LendingPoolConfiguratorUpdated_address_Event.OutputObject
  >;
  getEvent(
    key: "LendingPoolUpdated"
  ): TypedContractEvent<
    LendingPoolUpdatedEvent.InputTuple,
    LendingPoolUpdatedEvent.OutputTuple,
    LendingPoolUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "LendingPoolUpdated(address)"
  ): TypedContractEvent<
    LendingPoolUpdated_address_Event.InputTuple,
    LendingPoolUpdated_address_Event.OutputTuple,
    LendingPoolUpdated_address_Event.OutputObject
  >;
  getEvent(
    key: "LendingRateOracleUpdated"
  ): TypedContractEvent<
    LendingRateOracleUpdatedEvent.InputTuple,
    LendingRateOracleUpdatedEvent.OutputTuple,
    LendingRateOracleUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "LendingRateOracleUpdated(address)"
  ): TypedContractEvent<
    LendingRateOracleUpdated_address_Event.InputTuple,
    LendingRateOracleUpdated_address_Event.OutputTuple,
    LendingRateOracleUpdated_address_Event.OutputObject
  >;
  getEvent(
    key: "MarketIdSet"
  ): TypedContractEvent<
    MarketIdSetEvent.InputTuple,
    MarketIdSetEvent.OutputTuple,
    MarketIdSetEvent.OutputObject
  >;
  getEvent(
    key: "MarketIdSet(string)"
  ): TypedContractEvent<
    MarketIdSet_string_Event.InputTuple,
    MarketIdSet_string_Event.OutputTuple,
    MarketIdSet_string_Event.OutputObject
  >;
  getEvent(
    key: "PriceOracleUpdated"
  ): TypedContractEvent<
    PriceOracleUpdatedEvent.InputTuple,
    PriceOracleUpdatedEvent.OutputTuple,
    PriceOracleUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "PriceOracleUpdated(address)"
  ): TypedContractEvent<
    PriceOracleUpdated_address_Event.InputTuple,
    PriceOracleUpdated_address_Event.OutputTuple,
    PriceOracleUpdated_address_Event.OutputObject
  >;
  getEvent(
    key: "ProxyCreated"
  ): TypedContractEvent<
    ProxyCreatedEvent.InputTuple,
    ProxyCreatedEvent.OutputTuple,
    ProxyCreatedEvent.OutputObject
  >;
  getEvent(
    key: "ProxyCreated(bytes32,address)"
  ): TypedContractEvent<
    ProxyCreated_bytes32_address_Event.InputTuple,
    ProxyCreated_bytes32_address_Event.OutputTuple,
    ProxyCreated_bytes32_address_Event.OutputObject
  >;

  filters: {
    "AddressSet(bytes32,address,bool)": TypedContractEvent<
      AddressSetEvent.InputTuple,
      AddressSetEvent.OutputTuple,
      AddressSetEvent.OutputObject
    >;
    AddressSet: TypedContractEvent<
      AddressSetEvent.InputTuple,
      AddressSetEvent.OutputTuple,
      AddressSetEvent.OutputObject
    >;

    "ConfigurationAdminUpdated(address)": TypedContractEvent<
      ConfigurationAdminUpdatedEvent.InputTuple,
      ConfigurationAdminUpdatedEvent.OutputTuple,
      ConfigurationAdminUpdatedEvent.OutputObject
    >;
    ConfigurationAdminUpdated: TypedContractEvent<
      ConfigurationAdminUpdatedEvent.InputTuple,
      ConfigurationAdminUpdatedEvent.OutputTuple,
      ConfigurationAdminUpdatedEvent.OutputObject
    >;

    "EmergencyAdminUpdated(address)": TypedContractEvent<
      EmergencyAdminUpdatedEvent.InputTuple,
      EmergencyAdminUpdatedEvent.OutputTuple,
      EmergencyAdminUpdatedEvent.OutputObject
    >;
    EmergencyAdminUpdated: TypedContractEvent<
      EmergencyAdminUpdatedEvent.InputTuple,
      EmergencyAdminUpdatedEvent.OutputTuple,
      EmergencyAdminUpdatedEvent.OutputObject
    >;

    "LendingPoolCollateralManagerUpdated(address)": TypedContractEvent<
      LendingPoolCollateralManagerUpdatedEvent.InputTuple,
      LendingPoolCollateralManagerUpdatedEvent.OutputTuple,
      LendingPoolCollateralManagerUpdatedEvent.OutputObject
    >;
    LendingPoolCollateralManagerUpdated: TypedContractEvent<
      LendingPoolCollateralManagerUpdatedEvent.InputTuple,
      LendingPoolCollateralManagerUpdatedEvent.OutputTuple,
      LendingPoolCollateralManagerUpdatedEvent.OutputObject
    >;

    "LendingPoolConfiguratorUpdated(address)": TypedContractEvent<
      LendingPoolConfiguratorUpdatedEvent.InputTuple,
      LendingPoolConfiguratorUpdatedEvent.OutputTuple,
      LendingPoolConfiguratorUpdatedEvent.OutputObject
    >;
    LendingPoolConfiguratorUpdated: TypedContractEvent<
      LendingPoolConfiguratorUpdatedEvent.InputTuple,
      LendingPoolConfiguratorUpdatedEvent.OutputTuple,
      LendingPoolConfiguratorUpdatedEvent.OutputObject
    >;

    "LendingPoolUpdated(address)": TypedContractEvent<
      LendingPoolUpdatedEvent.InputTuple,
      LendingPoolUpdatedEvent.OutputTuple,
      LendingPoolUpdatedEvent.OutputObject
    >;
    LendingPoolUpdated: TypedContractEvent<
      LendingPoolUpdatedEvent.InputTuple,
      LendingPoolUpdatedEvent.OutputTuple,
      LendingPoolUpdatedEvent.OutputObject
    >;

    "LendingRateOracleUpdated(address)": TypedContractEvent<
      LendingRateOracleUpdatedEvent.InputTuple,
      LendingRateOracleUpdatedEvent.OutputTuple,
      LendingRateOracleUpdatedEvent.OutputObject
    >;
    LendingRateOracleUpdated: TypedContractEvent<
      LendingRateOracleUpdatedEvent.InputTuple,
      LendingRateOracleUpdatedEvent.OutputTuple,
      LendingRateOracleUpdatedEvent.OutputObject
    >;

    "MarketIdSet(string)": TypedContractEvent<
      MarketIdSetEvent.InputTuple,
      MarketIdSetEvent.OutputTuple,
      MarketIdSetEvent.OutputObject
    >;
    MarketIdSet: TypedContractEvent<
      MarketIdSetEvent.InputTuple,
      MarketIdSetEvent.OutputTuple,
      MarketIdSetEvent.OutputObject
    >;

    "PriceOracleUpdated(address)": TypedContractEvent<
      PriceOracleUpdatedEvent.InputTuple,
      PriceOracleUpdatedEvent.OutputTuple,
      PriceOracleUpdatedEvent.OutputObject
    >;
    PriceOracleUpdated: TypedContractEvent<
      PriceOracleUpdatedEvent.InputTuple,
      PriceOracleUpdatedEvent.OutputTuple,
      PriceOracleUpdatedEvent.OutputObject
    >;

    "ProxyCreated(bytes32,address)": TypedContractEvent<
      ProxyCreatedEvent.InputTuple,
      ProxyCreatedEvent.OutputTuple,
      ProxyCreatedEvent.OutputObject
    >;
    ProxyCreated: TypedContractEvent<
      ProxyCreatedEvent.InputTuple,
      ProxyCreatedEvent.OutputTuple,
      ProxyCreatedEvent.OutputObject
    >;
  };
}
