/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../../../../common";

export interface SubscriptionAPIInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "LINK"
      | "LINK()"
      | "LINK_NATIVE_FEED"
      | "LINK_NATIVE_FEED()"
      | "MAX_CONSUMERS"
      | "MAX_CONSUMERS()"
      | "acceptOwnership"
      | "acceptOwnership()"
      | "acceptSubscriptionOwnerTransfer"
      | "acceptSubscriptionOwnerTransfer(uint256)"
      | "addConsumer"
      | "addConsumer(uint256,address)"
      | "cancelSubscription"
      | "cancelSubscription(uint256,address)"
      | "createSubscription"
      | "createSubscription()"
      | "fundSubscriptionWithNative"
      | "fundSubscriptionWithNative(uint256)"
      | "getActiveSubscriptionIds"
      | "getActiveSubscriptionIds(uint256,uint256)"
      | "getSubscription"
      | "getSubscription(uint256)"
      | "onTokenTransfer"
      | "onTokenTransfer(address,uint256,bytes)"
      | "owner"
      | "owner()"
      | "ownerCancelSubscription"
      | "ownerCancelSubscription(uint256)"
      | "pendingRequestExists"
      | "pendingRequestExists(uint256)"
      | "recoverFunds"
      | "recoverFunds(address)"
      | "recoverNativeFunds"
      | "recoverNativeFunds(address)"
      | "removeConsumer"
      | "removeConsumer(uint256,address)"
      | "requestSubscriptionOwnerTransfer"
      | "requestSubscriptionOwnerTransfer(uint256,address)"
      | "s_config"
      | "s_config()"
      | "s_currentSubNonce"
      | "s_currentSubNonce()"
      | "s_totalBalance"
      | "s_totalBalance()"
      | "s_totalNativeBalance"
      | "s_totalNativeBalance()"
      | "setLINKAndLINKNativeFeed"
      | "setLINKAndLINKNativeFeed(address,address)"
      | "transferOwnership"
      | "transferOwnership(address)"
      | "withdraw"
      | "withdraw(address)"
      | "withdrawNative"
      | "withdrawNative(address)"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "FundsRecovered"
      | "FundsRecovered(address,uint256)"
      | "NativeFundsRecovered"
      | "NativeFundsRecovered(address,uint256)"
      | "OwnershipTransferRequested"
      | "OwnershipTransferRequested(address,address)"
      | "OwnershipTransferred"
      | "OwnershipTransferred(address,address)"
      | "SubscriptionCanceled"
      | "SubscriptionCanceled(uint256,address,uint256,uint256)"
      | "SubscriptionConsumerAdded"
      | "SubscriptionConsumerAdded(uint256,address)"
      | "SubscriptionConsumerRemoved"
      | "SubscriptionConsumerRemoved(uint256,address)"
      | "SubscriptionCreated"
      | "SubscriptionCreated(uint256,address)"
      | "SubscriptionFunded"
      | "SubscriptionFunded(uint256,uint256,uint256)"
      | "SubscriptionFundedWithNative"
      | "SubscriptionFundedWithNative(uint256,uint256,uint256)"
      | "SubscriptionOwnerTransferRequested"
      | "SubscriptionOwnerTransferRequested(uint256,address,address)"
      | "SubscriptionOwnerTransferred"
      | "SubscriptionOwnerTransferred(uint256,address,address)"
  ): EventFragment;

  encodeFunctionData(functionFragment: "LINK", values?: undefined): string;
  encodeFunctionData(functionFragment: "LINK()", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "LINK_NATIVE_FEED",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "LINK_NATIVE_FEED()",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_CONSUMERS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_CONSUMERS()",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "acceptOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "acceptOwnership()",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "acceptSubscriptionOwnerTransfer",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "acceptSubscriptionOwnerTransfer(uint256)",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "addConsumer",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addConsumer(uint256,address)",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelSubscription",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelSubscription(uint256,address)",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createSubscription",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createSubscription()",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "fundSubscriptionWithNative",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "fundSubscriptionWithNative(uint256)",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveSubscriptionIds",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveSubscriptionIds(uint256,uint256)",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSubscription",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSubscription(uint256)",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "onTokenTransfer",
    values: [AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "onTokenTransfer(address,uint256,bytes)",
    values: [AddressLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner()", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "ownerCancelSubscription",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "ownerCancelSubscription(uint256)",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "pendingRequestExists",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "pendingRequestExists(uint256)",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "recoverFunds",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "recoverFunds(address)",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "recoverNativeFunds",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "recoverNativeFunds(address)",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeConsumer",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeConsumer(uint256,address)",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requestSubscriptionOwnerTransfer",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requestSubscriptionOwnerTransfer(uint256,address)",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "s_config", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "s_config()",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "s_currentSubNonce",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "s_currentSubNonce()",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "s_totalBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "s_totalBalance()",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "s_totalNativeBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "s_totalNativeBalance()",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setLINKAndLINKNativeFeed",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setLINKAndLINKNativeFeed(address,address)",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership(address)",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw(address)",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawNative",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawNative(address)",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "LINK", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "LINK()", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "LINK_NATIVE_FEED",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "LINK_NATIVE_FEED()",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_CONSUMERS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_CONSUMERS()",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "acceptOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "acceptOwnership()",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "acceptSubscriptionOwnerTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "acceptSubscriptionOwnerTransfer(uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addConsumer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addConsumer(uint256,address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelSubscription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelSubscription(uint256,address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createSubscription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createSubscription()",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fundSubscriptionWithNative",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fundSubscriptionWithNative(uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveSubscriptionIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveSubscriptionIds(uint256,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSubscription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSubscription(uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onTokenTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onTokenTransfer(address,uint256,bytes)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner()", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "ownerCancelSubscription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ownerCancelSubscription(uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingRequestExists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingRequestExists(uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recoverFunds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recoverFunds(address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recoverNativeFunds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recoverNativeFunds(address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeConsumer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeConsumer(uint256,address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestSubscriptionOwnerTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestSubscriptionOwnerTransfer(uint256,address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "s_config", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "s_config()", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "s_currentSubNonce",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "s_currentSubNonce()",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "s_totalBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "s_totalBalance()",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "s_totalNativeBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "s_totalNativeBalance()",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setLINKAndLINKNativeFeed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setLINKAndLINKNativeFeed(address,address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership(address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdraw(address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawNative",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawNative(address)",
    data: BytesLike
  ): Result;
}

export namespace FundsRecoveredEvent {
  export type InputTuple = [to: AddressLike, amount: BigNumberish];
  export type OutputTuple = [to: string, amount: bigint];
  export interface OutputObject {
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NativeFundsRecoveredEvent {
  export type InputTuple = [to: AddressLike, amount: BigNumberish];
  export type OutputTuple = [to: string, amount: bigint];
  export interface OutputObject {
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferRequestedEvent {
  export type InputTuple = [from: AddressLike, to: AddressLike];
  export type OutputTuple = [from: string, to: string];
  export interface OutputObject {
    from: string;
    to: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [from: AddressLike, to: AddressLike];
  export type OutputTuple = [from: string, to: string];
  export interface OutputObject {
    from: string;
    to: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubscriptionCanceledEvent {
  export type InputTuple = [
    subId: BigNumberish,
    to: AddressLike,
    amountLink: BigNumberish,
    amountNative: BigNumberish
  ];
  export type OutputTuple = [
    subId: bigint,
    to: string,
    amountLink: bigint,
    amountNative: bigint
  ];
  export interface OutputObject {
    subId: bigint;
    to: string;
    amountLink: bigint;
    amountNative: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubscriptionConsumerAddedEvent {
  export type InputTuple = [subId: BigNumberish, consumer: AddressLike];
  export type OutputTuple = [subId: bigint, consumer: string];
  export interface OutputObject {
    subId: bigint;
    consumer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubscriptionConsumerRemovedEvent {
  export type InputTuple = [subId: BigNumberish, consumer: AddressLike];
  export type OutputTuple = [subId: bigint, consumer: string];
  export interface OutputObject {
    subId: bigint;
    consumer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubscriptionCreatedEvent {
  export type InputTuple = [subId: BigNumberish, owner: AddressLike];
  export type OutputTuple = [subId: bigint, owner: string];
  export interface OutputObject {
    subId: bigint;
    owner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubscriptionFundedEvent {
  export type InputTuple = [
    subId: BigNumberish,
    oldBalance: BigNumberish,
    newBalance: BigNumberish
  ];
  export type OutputTuple = [
    subId: bigint,
    oldBalance: bigint,
    newBalance: bigint
  ];
  export interface OutputObject {
    subId: bigint;
    oldBalance: bigint;
    newBalance: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubscriptionFundedWithNativeEvent {
  export type InputTuple = [
    subId: BigNumberish,
    oldNativeBalance: BigNumberish,
    newNativeBalance: BigNumberish
  ];
  export type OutputTuple = [
    subId: bigint,
    oldNativeBalance: bigint,
    newNativeBalance: bigint
  ];
  export interface OutputObject {
    subId: bigint;
    oldNativeBalance: bigint;
    newNativeBalance: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubscriptionOwnerTransferRequestedEvent {
  export type InputTuple = [
    subId: BigNumberish,
    from: AddressLike,
    to: AddressLike
  ];
  export type OutputTuple = [subId: bigint, from: string, to: string];
  export interface OutputObject {
    subId: bigint;
    from: string;
    to: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubscriptionOwnerTransferredEvent {
  export type InputTuple = [
    subId: BigNumberish,
    from: AddressLike,
    to: AddressLike
  ];
  export type OutputTuple = [subId: bigint, from: string, to: string];
  export interface OutputObject {
    subId: bigint;
    from: string;
    to: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SubscriptionAPI extends BaseContract {
  connect(runner?: ContractRunner | null): SubscriptionAPI;
  waitForDeployment(): Promise<this>;

  interface: SubscriptionAPIInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  LINK: TypedContractMethod<[], [string], "view">;

  "LINK()": TypedContractMethod<[], [string], "view">;

  LINK_NATIVE_FEED: TypedContractMethod<[], [string], "view">;

  "LINK_NATIVE_FEED()": TypedContractMethod<[], [string], "view">;

  MAX_CONSUMERS: TypedContractMethod<[], [bigint], "view">;

  "MAX_CONSUMERS()": TypedContractMethod<[], [bigint], "view">;

  acceptOwnership: TypedContractMethod<[], [void], "nonpayable">;

  "acceptOwnership()": TypedContractMethod<[], [void], "nonpayable">;

  acceptSubscriptionOwnerTransfer: TypedContractMethod<
    [subId: BigNumberish],
    [void],
    "nonpayable"
  >;

  "acceptSubscriptionOwnerTransfer(uint256)": TypedContractMethod<
    [subId: BigNumberish],
    [void],
    "nonpayable"
  >;

  addConsumer: TypedContractMethod<
    [subId: BigNumberish, consumer: AddressLike],
    [void],
    "nonpayable"
  >;

  "addConsumer(uint256,address)": TypedContractMethod<
    [subId: BigNumberish, consumer: AddressLike],
    [void],
    "nonpayable"
  >;

  cancelSubscription: TypedContractMethod<
    [subId: BigNumberish, to: AddressLike],
    [void],
    "nonpayable"
  >;

  "cancelSubscription(uint256,address)": TypedContractMethod<
    [subId: BigNumberish, to: AddressLike],
    [void],
    "nonpayable"
  >;

  createSubscription: TypedContractMethod<[], [bigint], "nonpayable">;

  "createSubscription()": TypedContractMethod<[], [bigint], "nonpayable">;

  fundSubscriptionWithNative: TypedContractMethod<
    [subId: BigNumberish],
    [void],
    "payable"
  >;

  "fundSubscriptionWithNative(uint256)": TypedContractMethod<
    [subId: BigNumberish],
    [void],
    "payable"
  >;

  getActiveSubscriptionIds: TypedContractMethod<
    [startIndex: BigNumberish, maxCount: BigNumberish],
    [bigint[]],
    "view"
  >;

  "getActiveSubscriptionIds(uint256,uint256)": TypedContractMethod<
    [startIndex: BigNumberish, maxCount: BigNumberish],
    [bigint[]],
    "view"
  >;

  getSubscription: TypedContractMethod<
    [subId: BigNumberish],
    [
      [bigint, bigint, bigint, string, string[]] & {
        balance: bigint;
        nativeBalance: bigint;
        reqCount: bigint;
        subOwner: string;
        consumers: string[];
      }
    ],
    "view"
  >;

  "getSubscription(uint256)": TypedContractMethod<
    [subId: BigNumberish],
    [
      [bigint, bigint, bigint, string, string[]] & {
        balance: bigint;
        nativeBalance: bigint;
        reqCount: bigint;
        subOwner: string;
        consumers: string[];
      }
    ],
    "view"
  >;

  onTokenTransfer: TypedContractMethod<
    [arg0: AddressLike, amount: BigNumberish, data: BytesLike],
    [void],
    "nonpayable"
  >;

  "onTokenTransfer(address,uint256,bytes)": TypedContractMethod<
    [arg0: AddressLike, amount: BigNumberish, data: BytesLike],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  "owner()": TypedContractMethod<[], [string], "view">;

  ownerCancelSubscription: TypedContractMethod<
    [subId: BigNumberish],
    [void],
    "nonpayable"
  >;

  "ownerCancelSubscription(uint256)": TypedContractMethod<
    [subId: BigNumberish],
    [void],
    "nonpayable"
  >;

  pendingRequestExists: TypedContractMethod<
    [subId: BigNumberish],
    [boolean],
    "view"
  >;

  "pendingRequestExists(uint256)": TypedContractMethod<
    [subId: BigNumberish],
    [boolean],
    "view"
  >;

  recoverFunds: TypedContractMethod<[to: AddressLike], [void], "nonpayable">;

  "recoverFunds(address)": TypedContractMethod<
    [to: AddressLike],
    [void],
    "nonpayable"
  >;

  recoverNativeFunds: TypedContractMethod<
    [to: AddressLike],
    [void],
    "nonpayable"
  >;

  "recoverNativeFunds(address)": TypedContractMethod<
    [to: AddressLike],
    [void],
    "nonpayable"
  >;

  removeConsumer: TypedContractMethod<
    [subId: BigNumberish, consumer: AddressLike],
    [void],
    "nonpayable"
  >;

  "removeConsumer(uint256,address)": TypedContractMethod<
    [subId: BigNumberish, consumer: AddressLike],
    [void],
    "nonpayable"
  >;

  requestSubscriptionOwnerTransfer: TypedContractMethod<
    [subId: BigNumberish, newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  "requestSubscriptionOwnerTransfer(uint256,address)": TypedContractMethod<
    [subId: BigNumberish, newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  s_config: TypedContractMethod<
    [],
    [
      [
        bigint,
        bigint,
        boolean,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        minimumRequestConfirmations: bigint;
        maxGasLimit: bigint;
        reentrancyLock: boolean;
        stalenessSeconds: bigint;
        gasAfterPaymentCalculation: bigint;
        fulfillmentFlatFeeNativePPM: bigint;
        fulfillmentFlatFeeLinkDiscountPPM: bigint;
        nativePremiumPercentage: bigint;
        linkPremiumPercentage: bigint;
      }
    ],
    "view"
  >;

  "s_config()": TypedContractMethod<
    [],
    [
      [
        bigint,
        bigint,
        boolean,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        minimumRequestConfirmations: bigint;
        maxGasLimit: bigint;
        reentrancyLock: boolean;
        stalenessSeconds: bigint;
        gasAfterPaymentCalculation: bigint;
        fulfillmentFlatFeeNativePPM: bigint;
        fulfillmentFlatFeeLinkDiscountPPM: bigint;
        nativePremiumPercentage: bigint;
        linkPremiumPercentage: bigint;
      }
    ],
    "view"
  >;

  s_currentSubNonce: TypedContractMethod<[], [bigint], "view">;

  "s_currentSubNonce()": TypedContractMethod<[], [bigint], "view">;

  s_totalBalance: TypedContractMethod<[], [bigint], "view">;

  "s_totalBalance()": TypedContractMethod<[], [bigint], "view">;

  s_totalNativeBalance: TypedContractMethod<[], [bigint], "view">;

  "s_totalNativeBalance()": TypedContractMethod<[], [bigint], "view">;

  setLINKAndLINKNativeFeed: TypedContractMethod<
    [link: AddressLike, linkNativeFeed: AddressLike],
    [void],
    "nonpayable"
  >;

  "setLINKAndLINKNativeFeed(address,address)": TypedContractMethod<
    [link: AddressLike, linkNativeFeed: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [to: AddressLike],
    [void],
    "nonpayable"
  >;

  "transferOwnership(address)": TypedContractMethod<
    [to: AddressLike],
    [void],
    "nonpayable"
  >;

  withdraw: TypedContractMethod<[recipient: AddressLike], [void], "nonpayable">;

  "withdraw(address)": TypedContractMethod<
    [recipient: AddressLike],
    [void],
    "nonpayable"
  >;

  withdrawNative: TypedContractMethod<
    [recipient: AddressLike],
    [void],
    "nonpayable"
  >;

  "withdrawNative(address)": TypedContractMethod<
    [recipient: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "LINK"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "LINK()"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "LINK_NATIVE_FEED"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "LINK_NATIVE_FEED()"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "MAX_CONSUMERS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_CONSUMERS()"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "acceptOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "acceptOwnership()"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "acceptSubscriptionOwnerTransfer"
  ): TypedContractMethod<[subId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "acceptSubscriptionOwnerTransfer(uint256)"
  ): TypedContractMethod<[subId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "addConsumer"
  ): TypedContractMethod<
    [subId: BigNumberish, consumer: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addConsumer(uint256,address)"
  ): TypedContractMethod<
    [subId: BigNumberish, consumer: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "cancelSubscription"
  ): TypedContractMethod<
    [subId: BigNumberish, to: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "cancelSubscription(uint256,address)"
  ): TypedContractMethod<
    [subId: BigNumberish, to: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createSubscription"
  ): TypedContractMethod<[], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "createSubscription()"
  ): TypedContractMethod<[], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "fundSubscriptionWithNative"
  ): TypedContractMethod<[subId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "fundSubscriptionWithNative(uint256)"
  ): TypedContractMethod<[subId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "getActiveSubscriptionIds"
  ): TypedContractMethod<
    [startIndex: BigNumberish, maxCount: BigNumberish],
    [bigint[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getActiveSubscriptionIds(uint256,uint256)"
  ): TypedContractMethod<
    [startIndex: BigNumberish, maxCount: BigNumberish],
    [bigint[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSubscription"
  ): TypedContractMethod<
    [subId: BigNumberish],
    [
      [bigint, bigint, bigint, string, string[]] & {
        balance: bigint;
        nativeBalance: bigint;
        reqCount: bigint;
        subOwner: string;
        consumers: string[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSubscription(uint256)"
  ): TypedContractMethod<
    [subId: BigNumberish],
    [
      [bigint, bigint, bigint, string, string[]] & {
        balance: bigint;
        nativeBalance: bigint;
        reqCount: bigint;
        subOwner: string;
        consumers: string[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "onTokenTransfer"
  ): TypedContractMethod<
    [arg0: AddressLike, amount: BigNumberish, data: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "onTokenTransfer(address,uint256,bytes)"
  ): TypedContractMethod<
    [arg0: AddressLike, amount: BigNumberish, data: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner()"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ownerCancelSubscription"
  ): TypedContractMethod<[subId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "ownerCancelSubscription(uint256)"
  ): TypedContractMethod<[subId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "pendingRequestExists"
  ): TypedContractMethod<[subId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "pendingRequestExists(uint256)"
  ): TypedContractMethod<[subId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "recoverFunds"
  ): TypedContractMethod<[to: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "recoverFunds(address)"
  ): TypedContractMethod<[to: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "recoverNativeFunds"
  ): TypedContractMethod<[to: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "recoverNativeFunds(address)"
  ): TypedContractMethod<[to: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeConsumer"
  ): TypedContractMethod<
    [subId: BigNumberish, consumer: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "removeConsumer(uint256,address)"
  ): TypedContractMethod<
    [subId: BigNumberish, consumer: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requestSubscriptionOwnerTransfer"
  ): TypedContractMethod<
    [subId: BigNumberish, newOwner: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requestSubscriptionOwnerTransfer(uint256,address)"
  ): TypedContractMethod<
    [subId: BigNumberish, newOwner: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "s_config"
  ): TypedContractMethod<
    [],
    [
      [
        bigint,
        bigint,
        boolean,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        minimumRequestConfirmations: bigint;
        maxGasLimit: bigint;
        reentrancyLock: boolean;
        stalenessSeconds: bigint;
        gasAfterPaymentCalculation: bigint;
        fulfillmentFlatFeeNativePPM: bigint;
        fulfillmentFlatFeeLinkDiscountPPM: bigint;
        nativePremiumPercentage: bigint;
        linkPremiumPercentage: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "s_config()"
  ): TypedContractMethod<
    [],
    [
      [
        bigint,
        bigint,
        boolean,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        minimumRequestConfirmations: bigint;
        maxGasLimit: bigint;
        reentrancyLock: boolean;
        stalenessSeconds: bigint;
        gasAfterPaymentCalculation: bigint;
        fulfillmentFlatFeeNativePPM: bigint;
        fulfillmentFlatFeeLinkDiscountPPM: bigint;
        nativePremiumPercentage: bigint;
        linkPremiumPercentage: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "s_currentSubNonce"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "s_currentSubNonce()"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "s_totalBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "s_totalBalance()"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "s_totalNativeBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "s_totalNativeBalance()"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "setLINKAndLINKNativeFeed"
  ): TypedContractMethod<
    [link: AddressLike, linkNativeFeed: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setLINKAndLINKNativeFeed(address,address)"
  ): TypedContractMethod<
    [link: AddressLike, linkNativeFeed: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[to: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership(address)"
  ): TypedContractMethod<[to: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[recipient: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdraw(address)"
  ): TypedContractMethod<[recipient: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawNative"
  ): TypedContractMethod<[recipient: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawNative(address)"
  ): TypedContractMethod<[recipient: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "FundsRecovered"
  ): TypedContractEvent<
    FundsRecoveredEvent.InputTuple,
    FundsRecoveredEvent.OutputTuple,
    FundsRecoveredEvent.OutputObject
  >;
  getEvent(
    key: "FundsRecovered(address,uint256)"
  ): TypedContractEvent<
    FundsRecovered_address_uint256_Event.InputTuple,
    FundsRecovered_address_uint256_Event.OutputTuple,
    FundsRecovered_address_uint256_Event.OutputObject
  >;
  getEvent(
    key: "NativeFundsRecovered"
  ): TypedContractEvent<
    NativeFundsRecoveredEvent.InputTuple,
    NativeFundsRecoveredEvent.OutputTuple,
    NativeFundsRecoveredEvent.OutputObject
  >;
  getEvent(
    key: "NativeFundsRecovered(address,uint256)"
  ): TypedContractEvent<
    NativeFundsRecovered_address_uint256_Event.InputTuple,
    NativeFundsRecovered_address_uint256_Event.OutputTuple,
    NativeFundsRecovered_address_uint256_Event.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferRequested"
  ): TypedContractEvent<
    OwnershipTransferRequestedEvent.InputTuple,
    OwnershipTransferRequestedEvent.OutputTuple,
    OwnershipTransferRequestedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferRequested(address,address)"
  ): TypedContractEvent<
    OwnershipTransferRequested_address_address_Event.InputTuple,
    OwnershipTransferRequested_address_address_Event.OutputTuple,
    OwnershipTransferRequested_address_address_Event.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred(address,address)"
  ): TypedContractEvent<
    OwnershipTransferred_address_address_Event.InputTuple,
    OwnershipTransferred_address_address_Event.OutputTuple,
    OwnershipTransferred_address_address_Event.OutputObject
  >;
  getEvent(
    key: "SubscriptionCanceled"
  ): TypedContractEvent<
    SubscriptionCanceledEvent.InputTuple,
    SubscriptionCanceledEvent.OutputTuple,
    SubscriptionCanceledEvent.OutputObject
  >;
  getEvent(
    key: "SubscriptionCanceled(uint256,address,uint256,uint256)"
  ): TypedContractEvent<
    SubscriptionCanceled_uint256_address_uint256_uint256_Event.InputTuple,
    SubscriptionCanceled_uint256_address_uint256_uint256_Event.OutputTuple,
    SubscriptionCanceled_uint256_address_uint256_uint256_Event.OutputObject
  >;
  getEvent(
    key: "SubscriptionConsumerAdded"
  ): TypedContractEvent<
    SubscriptionConsumerAddedEvent.InputTuple,
    SubscriptionConsumerAddedEvent.OutputTuple,
    SubscriptionConsumerAddedEvent.OutputObject
  >;
  getEvent(
    key: "SubscriptionConsumerAdded(uint256,address)"
  ): TypedContractEvent<
    SubscriptionConsumerAdded_uint256_address_Event.InputTuple,
    SubscriptionConsumerAdded_uint256_address_Event.OutputTuple,
    SubscriptionConsumerAdded_uint256_address_Event.OutputObject
  >;
  getEvent(
    key: "SubscriptionConsumerRemoved"
  ): TypedContractEvent<
    SubscriptionConsumerRemovedEvent.InputTuple,
    SubscriptionConsumerRemovedEvent.OutputTuple,
    SubscriptionConsumerRemovedEvent.OutputObject
  >;
  getEvent(
    key: "SubscriptionConsumerRemoved(uint256,address)"
  ): TypedContractEvent<
    SubscriptionConsumerRemoved_uint256_address_Event.InputTuple,
    SubscriptionConsumerRemoved_uint256_address_Event.OutputTuple,
    SubscriptionConsumerRemoved_uint256_address_Event.OutputObject
  >;
  getEvent(
    key: "SubscriptionCreated"
  ): TypedContractEvent<
    SubscriptionCreatedEvent.InputTuple,
    SubscriptionCreatedEvent.OutputTuple,
    SubscriptionCreatedEvent.OutputObject
  >;
  getEvent(
    key: "SubscriptionCreated(uint256,address)"
  ): TypedContractEvent<
    SubscriptionCreated_uint256_address_Event.InputTuple,
    SubscriptionCreated_uint256_address_Event.OutputTuple,
    SubscriptionCreated_uint256_address_Event.OutputObject
  >;
  getEvent(
    key: "SubscriptionFunded"
  ): TypedContractEvent<
    SubscriptionFundedEvent.InputTuple,
    SubscriptionFundedEvent.OutputTuple,
    SubscriptionFundedEvent.OutputObject
  >;
  getEvent(
    key: "SubscriptionFunded(uint256,uint256,uint256)"
  ): TypedContractEvent<
    SubscriptionFunded_uint256_uint256_uint256_Event.InputTuple,
    SubscriptionFunded_uint256_uint256_uint256_Event.OutputTuple,
    SubscriptionFunded_uint256_uint256_uint256_Event.OutputObject
  >;
  getEvent(
    key: "SubscriptionFundedWithNative"
  ): TypedContractEvent<
    SubscriptionFundedWithNativeEvent.InputTuple,
    SubscriptionFundedWithNativeEvent.OutputTuple,
    SubscriptionFundedWithNativeEvent.OutputObject
  >;
  getEvent(
    key: "SubscriptionFundedWithNative(uint256,uint256,uint256)"
  ): TypedContractEvent<
    SubscriptionFundedWithNative_uint256_uint256_uint256_Event.InputTuple,
    SubscriptionFundedWithNative_uint256_uint256_uint256_Event.OutputTuple,
    SubscriptionFundedWithNative_uint256_uint256_uint256_Event.OutputObject
  >;
  getEvent(
    key: "SubscriptionOwnerTransferRequested"
  ): TypedContractEvent<
    SubscriptionOwnerTransferRequestedEvent.InputTuple,
    SubscriptionOwnerTransferRequestedEvent.OutputTuple,
    SubscriptionOwnerTransferRequestedEvent.OutputObject
  >;
  getEvent(
    key: "SubscriptionOwnerTransferRequested(uint256,address,address)"
  ): TypedContractEvent<
    SubscriptionOwnerTransferRequested_uint256_address_address_Event.InputTuple,
    SubscriptionOwnerTransferRequested_uint256_address_address_Event.OutputTuple,
    SubscriptionOwnerTransferRequested_uint256_address_address_Event.OutputObject
  >;
  getEvent(
    key: "SubscriptionOwnerTransferred"
  ): TypedContractEvent<
    SubscriptionOwnerTransferredEvent.InputTuple,
    SubscriptionOwnerTransferredEvent.OutputTuple,
    SubscriptionOwnerTransferredEvent.OutputObject
  >;
  getEvent(
    key: "SubscriptionOwnerTransferred(uint256,address,address)"
  ): TypedContractEvent<
    SubscriptionOwnerTransferred_uint256_address_address_Event.InputTuple,
    SubscriptionOwnerTransferred_uint256_address_address_Event.OutputTuple,
    SubscriptionOwnerTransferred_uint256_address_address_Event.OutputObject
  >;

  filters: {
    "FundsRecovered(address,uint256)": TypedContractEvent<
      FundsRecoveredEvent.InputTuple,
      FundsRecoveredEvent.OutputTuple,
      FundsRecoveredEvent.OutputObject
    >;
    FundsRecovered: TypedContractEvent<
      FundsRecoveredEvent.InputTuple,
      FundsRecoveredEvent.OutputTuple,
      FundsRecoveredEvent.OutputObject
    >;

    "NativeFundsRecovered(address,uint256)": TypedContractEvent<
      NativeFundsRecoveredEvent.InputTuple,
      NativeFundsRecoveredEvent.OutputTuple,
      NativeFundsRecoveredEvent.OutputObject
    >;
    NativeFundsRecovered: TypedContractEvent<
      NativeFundsRecoveredEvent.InputTuple,
      NativeFundsRecoveredEvent.OutputTuple,
      NativeFundsRecoveredEvent.OutputObject
    >;

    "OwnershipTransferRequested(address,address)": TypedContractEvent<
      OwnershipTransferRequestedEvent.InputTuple,
      OwnershipTransferRequestedEvent.OutputTuple,
      OwnershipTransferRequestedEvent.OutputObject
    >;
    OwnershipTransferRequested: TypedContractEvent<
      OwnershipTransferRequestedEvent.InputTuple,
      OwnershipTransferRequestedEvent.OutputTuple,
      OwnershipTransferRequestedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "SubscriptionCanceled(uint256,address,uint256,uint256)": TypedContractEvent<
      SubscriptionCanceledEvent.InputTuple,
      SubscriptionCanceledEvent.OutputTuple,
      SubscriptionCanceledEvent.OutputObject
    >;
    SubscriptionCanceled: TypedContractEvent<
      SubscriptionCanceledEvent.InputTuple,
      SubscriptionCanceledEvent.OutputTuple,
      SubscriptionCanceledEvent.OutputObject
    >;

    "SubscriptionConsumerAdded(uint256,address)": TypedContractEvent<
      SubscriptionConsumerAddedEvent.InputTuple,
      SubscriptionConsumerAddedEvent.OutputTuple,
      SubscriptionConsumerAddedEvent.OutputObject
    >;
    SubscriptionConsumerAdded: TypedContractEvent<
      SubscriptionConsumerAddedEvent.InputTuple,
      SubscriptionConsumerAddedEvent.OutputTuple,
      SubscriptionConsumerAddedEvent.OutputObject
    >;

    "SubscriptionConsumerRemoved(uint256,address)": TypedContractEvent<
      SubscriptionConsumerRemovedEvent.InputTuple,
      SubscriptionConsumerRemovedEvent.OutputTuple,
      SubscriptionConsumerRemovedEvent.OutputObject
    >;
    SubscriptionConsumerRemoved: TypedContractEvent<
      SubscriptionConsumerRemovedEvent.InputTuple,
      SubscriptionConsumerRemovedEvent.OutputTuple,
      SubscriptionConsumerRemovedEvent.OutputObject
    >;

    "SubscriptionCreated(uint256,address)": TypedContractEvent<
      SubscriptionCreatedEvent.InputTuple,
      SubscriptionCreatedEvent.OutputTuple,
      SubscriptionCreatedEvent.OutputObject
    >;
    SubscriptionCreated: TypedContractEvent<
      SubscriptionCreatedEvent.InputTuple,
      SubscriptionCreatedEvent.OutputTuple,
      SubscriptionCreatedEvent.OutputObject
    >;

    "SubscriptionFunded(uint256,uint256,uint256)": TypedContractEvent<
      SubscriptionFundedEvent.InputTuple,
      SubscriptionFundedEvent.OutputTuple,
      SubscriptionFundedEvent.OutputObject
    >;
    SubscriptionFunded: TypedContractEvent<
      SubscriptionFundedEvent.InputTuple,
      SubscriptionFundedEvent.OutputTuple,
      SubscriptionFundedEvent.OutputObject
    >;

    "SubscriptionFundedWithNative(uint256,uint256,uint256)": TypedContractEvent<
      SubscriptionFundedWithNativeEvent.InputTuple,
      SubscriptionFundedWithNativeEvent.OutputTuple,
      SubscriptionFundedWithNativeEvent.OutputObject
    >;
    SubscriptionFundedWithNative: TypedContractEvent<
      SubscriptionFundedWithNativeEvent.InputTuple,
      SubscriptionFundedWithNativeEvent.OutputTuple,
      SubscriptionFundedWithNativeEvent.OutputObject
    >;

    "SubscriptionOwnerTransferRequested(uint256,address,address)": TypedContractEvent<
      SubscriptionOwnerTransferRequestedEvent.InputTuple,
      SubscriptionOwnerTransferRequestedEvent.OutputTuple,
      SubscriptionOwnerTransferRequestedEvent.OutputObject
    >;
    SubscriptionOwnerTransferRequested: TypedContractEvent<
      SubscriptionOwnerTransferRequestedEvent.InputTuple,
      SubscriptionOwnerTransferRequestedEvent.OutputTuple,
      SubscriptionOwnerTransferRequestedEvent.OutputObject
    >;

    "SubscriptionOwnerTransferred(uint256,address,address)": TypedContractEvent<
      SubscriptionOwnerTransferredEvent.InputTuple,
      SubscriptionOwnerTransferredEvent.OutputTuple,
      SubscriptionOwnerTransferredEvent.OutputObject
    >;
    SubscriptionOwnerTransferred: TypedContractEvent<
      SubscriptionOwnerTransferredEvent.InputTuple,
      SubscriptionOwnerTransferredEvent.OutputTuple,
      SubscriptionOwnerTransferredEvent.OutputObject
    >;
  };
}
